// ═══════════════════════════════════════════════════════════
// RECOLLECT — Layer B Narrative Data
// Auto-generated from Layer B markdown files
// ═══════════════════════════════════════════════════════════

export interface NarrativeSection {
  title: string;
  body: string;  // HTML content
}

export interface TopicNarrative {
  narrative: NarrativeSection[];
  narrativeCN: NarrativeSection[];
}

export const narrativeData: Record<string, TopicNarrative> = {
  'origins': {
    narrative: [
      { title: "", body: "<p>There's something almost impossible to grasp about a celebration that has continued, unbroken, for over three thousand years.</p><p>Think about that for a moment. When the ancient Egyptians were building their final pyramids, Chinese families were already gathering at year's end to share meals and honor their ancestors. When Rome was still a collection of villages on the Tiber, Chinese courts were conducting elaborate New Year rituals.</p><p>And tonight—this very night, as you read these words—somewhere in the world, a family is preparing for the same celebration their ancestors observed thirty centuries ago.</p><p>How did this happen? Where did it all begin?</p>" },
      { title: "Following the Moon", body: "<p>The first thing to understand is the calendar.</p><p>Chinese New Year doesn't fall on January 1st, and it doesn't fall on the same date each year. Instead, it follows the ancient lunisolar calendar—a system that tracks both the moon's phases and the sun's journey through the seasons.</p><p>Each month begins with the new moon. The first day of the first month—New Year's Day—must therefore fall on a new moon, sometime between late January and mid-February.</p><p>But here's what's fascinating: this isn't arbitrary. This calendar was designed by astronomers who studied the heavens with remarkable precision, creating a system that kept farmers aligned with planting seasons and everyone aligned with the celestial rhythms that governed traditional Chinese cosmology.</p><p>When Emperor Wu of Han standardized this calendar in 104 BCE, he wasn't inventing something new. He was codifying practices that had already been evolving for a thousand years.</p>" },
      { title: "The Deep Roots", body: "<p>The earliest New Year observances emerged from the rhythms of agricultural life.</p><p>Imagine a farming community in ancient China, perhaps 3,500 years ago during the Shang Dynasty. The harvest is complete. The grain is stored. Winter has arrived, and the land lies dormant. This is a moment of profound transition—the old cycle has ended, the new has not yet begun.</p><p>What do you do at such a moment? You give thanks. You make offerings to the gods who sent rain and sun at the right times. You honor your ancestors, whose spirits continue to watch over their descendants. You ask for blessings in the year to come.</p><p>Oracle bones from this period record exactly these activities. Ancient kings consulted the spirits about next year's harvests, next year's fortunes. The year's end was a time of communication between worlds.</p>" },
      { title: "The Sound of Renewal", body: "<p>One of the oldest New Year customs is also one of the loudest.</p><p>Before gunpowder, people discovered that throwing bamboo segments into fires created sharp, explosive cracks. The hollow chambers would heat, the air inside would expand, and—bang—the bamboo would split with a sound like thunder.</p><p>Why do this? Because spirits fear loud noises. Because darkness flees from fire and sound. Because at the threshold of the new year, when boundaries between worlds grow thin, you need all the protection you can get.</p><p>The word for firecracker—爆竹, bàozhú—literally means \"exploding bamboo,\" preserving this ancient practice in language even though gunpowder replaced bamboo over a millennium ago.</p>" },
      { title: "A Story Arrives Late", body: "<p>You've probably heard the legend of the Nián beast—the monster that emerged each New Year's Eve to terrorize villages until an old man revealed its weaknesses: red color, bright fire, loud noise.</p><p>It's a wonderful story. It explains so much.</p><p>But here's something scholars have noticed: this story doesn't appear in any ancient text.</p><p>The Nián beast legend seems to have emerged in the early twentieth century, perhaps created to explain customs whose original meanings had grown obscure. It's a modern folk etymology—a story invented to make sense of practices far older than the story itself.</p><p>Does this make the legend false? Not exactly. It makes it a different kind of truth—a story that captures the spirit of New Year customs even if it didn't generate them. Light triumphing over darkness. Community solidarity against fear. Hope renewed annually.</p>" },
      { title: "The Circle of Animals", body: "<p>And then there's the zodiac.</p><p>Twelve animals. Twelve years. An endless cycle stretching back through time and forward into the future.</p><p>Rat, Ox, Tiger, Rabbit, Dragon, Snake, Horse, Goat, Monkey, Rooster, Dog, Pig—then back to Rat again.</p><p>Where did this system come from? The origins are genuinely mysterious. The twelve animals appear in Chinese sources by at least the Han Dynasty, but similar zodiac systems exist across Asia, suggesting ancient cultural exchanges whose details are lost.</p><p>The system grows more complex when combined with the Five Elements: Wood, Fire, Earth, Metal, Water. Each element governs two consecutive years, creating a sixty-year grand cycle before any combination repeats.</p><p>2026 is a Fire Horse year—the horse's dynamism combined with fire's intensity.</p>" },
      { title: "What Continues", body: "<p>In 2024, UNESCO recognized Spring Festival as part of the Intangible Cultural Heritage of Humanity. The designation acknowledged what anyone who has participated already knows: this is one of humanity's great living traditions.</p><p>The origins we've traced—the ancient sacrifices, the lunar calendar, the exorcism rituals, the bamboo explosions—these aren't museum pieces. They're the foundation of something that continues to grow.</p><p>When a family gathers for reunion dinner tonight, they're participating in a ritual older than most nations. When firecrackers echo through city streets, they're continuing a conversation with the spirits that began before writing existed.</p><p>Three thousand years. And still counting.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>一个延续了三千多年、从未中断的庆典——这几乎是难以想象的事情。</p><p>请想一想。当古埃及人建造最后一批金字塔时，中国的家庭已经在岁末聚会，共享宴席，祭拜祖先。当罗马还只是台伯河畔的几个村落时，中国宫廷已在举行隆重的新年仪式。</p><p>而今夜——就在你读到这些文字的此刻——世界某处的某个家庭，正在准备他们的祖先三十个世纪前就在庆祝的同一个节日。</p><p>这是怎么发生的？一切始于何处？</p>" },
      { title: "追随月亮", body: "<p>首先要理解的是历法。</p><p>中国新年不在1月1日，每年的日期也不固定。它遵循的是古老的农历——一种同时追踪月相和太阳季节运行的阴阳合历体系。</p><p>每个月始于新月。正月初一——新年第一天——因此必须落在新月之日，这就是为什么它在公历上会在1月下旬到2月中旬之间\"移动\"。</p><p>但妙处在于：这不是混乱，而是另一种秩序。这套历法是由观测天象精确入微的天文学家设计的，它使农民与播种季节保持一致，使所有人与主宰传统中国宇宙观的天体节律保持一致。</p><p>当汉武帝于公元前104年将这套历法标准化时，他并非发明新事物，而是将已经演变了千年的实践编纂成典。</p>" },
      { title: "深处的根系", body: "<p>最早的新年庆典源于农业生活的节律。</p><p>想象三千五百年前商朝时期的一个农耕社区。收获已经完成，谷物已经储藏，冬天已经到来，大地陷入沉眠。这是一个深刻转换的时刻——旧的循环已经结束，新的尚未开始。</p><p>在这样的时刻你会做什么？你感谢。你向在恰当时候送来雨水和阳光的神灵献祭。你敬拜祖先，他们的灵魂仍在守护着子孙后代。你祈求来年的祝福。</p><p>这个时期的甲骨文确切地记录了这些活动。古代帝王向神灵询问来年的收成、来年的命运。岁末是沟通人间与神界的时刻。</p>" },
      { title: "更新之声", body: "<p>最古老的新年习俗之一，也是最喧闹的。</p><p>在火药出现之前，人们发现把竹节扔进火里会产生尖锐的爆裂声——中空的竹腔受热，内部空气膨胀，然后——砰——竹子裂开，发出雷鸣般的响声。</p><p>为什么要这样做？因为鬼魂害怕巨响。因为黑暗在火光和声音面前逃遁。因为在新年的门槛上，当两个世界之间的边界变得稀薄时，你需要一切能得到的保护。</p><p>\"爆竹\"这个词——字面意思就是\"爆裂的竹子\"——即使火药在一千多年前就取代了竹子，语言仍然保存着这一古老的实践。</p>" },
      { title: "姗姗来迟的故事", body: "<p>你可能听过年兽的传说——那头每年除夕出现、恐吓村民的怪物，直到一位老人揭示了它的弱点：红色、火光、巨响。</p><p>这是一个精彩的故事。它解释了太多。</p><p>但学者们注意到一件事：这个故事没有出现在任何古籍中。</p><p>年兽传说似乎出现于二十世纪初，也许是为了解释那些原始意义已经模糊的习俗而创造的。它是一种现代民间词源学——一个为理解远比故事本身古老的实践而发明的叙事。</p><p>这是否使传说变得虚假？并非如此。它使传说成为另一种真实——一个捕捉新年习俗精神的故事，即使它并没有创造这些习俗。光明战胜黑暗。社区团结抵御恐惧。希望年年更新。</p>" },
      { title: "动物之环", body: "<p>然后是生肖。</p><p>十二种动物。十二年。一个无始无终的循环。</p><p>鼠、牛、虎、兔、龙、蛇、马、羊、猴、鸡、狗、猪——然后又回到鼠。</p><p>这个体系从何而来？起源确实是个谜。十二动物至少在汉代就出现在中国文献中，但类似的生肖体系存在于东亚和中亚各地，暗示着已经失落细节的古代文化交流。</p><p>当与五行——木、火、土、金、水——结合时，系统变得更加复杂。每种元素主宰连续两年，形成一个六十年的大循环，之后任何组合才会重复。</p><p>2026年是丙午火马年——马的活力与火的强烈相结合。</p>" },
      { title: "延续之物", body: "<p>2024年，联合国教科文组织将春节列入人类非物质文化遗产。这一认定承认了任何参与过这个节日的人已经知道的事实：这是人类伟大的活态传统之一。</p><p>我们追溯的这些起源——古老的祭祀、农历、驱邪仪式、竹子爆响——这些不是博物馆展品。它们是某种持续生长之物的根基。</p><p>当一个家庭今晚聚在一起吃年夜饭时，他们参与的是一个比大多数国家都古老的仪式。当爆竹声回荡在城市街道时，他们延续的是一场在文字存在之前就开始的与神灵的对话。</p><p>三千年。而且仍在继续。</p>" },
      { title: "", body: "<p>这是我们探索中国新年之旅的第一章——一段将带我们穿越历史与地理、习俗与商业、平凡与神奇的旅程。</p>" },
    ],
  },
  'evolution': {
    narrative: [
      { title: "", body: "<p>There is a moment, every year, when time folds back on itself.</p><p>Trains fill with migrant workers heading home. Markets overflow with red paper and dried meats. The rhythm of daily life shifts, almost audibly, as if the entire country is exhaling before a deep breath.</p><p>This is the Spring Festival—or the Lunar New Year, or the Chinese New Year, depending on who you ask and what politics they carry. But before we argue about what to call it, perhaps we should ask: how did it get here?</p><p>The answer is stranger than you might expect.</p>" },
      { title: "Before It Had a Name", body: "<p>For most of Chinese history, there was no \"Spring Festival.\" There was simply *Nian*—the Year. It was not a holiday within the year; it was the year itself, the hinge upon which all time turned.</p><p>The celebration evolved through dynasties without needing a formal name. During the Han Dynasty, the rituals became more elaborate—court ceremonies, ancestral rites, communal feasts. By the Tang and Song periods, fireworks and lantern displays had been added. The Ming and Qing courts turned New Year observances into grand state spectacles lasting weeks.</p><p>But throughout all of this, the celebration simply was. It needed no branding. When the year ended, you observed it. That was as natural as breathing.</p>" },
      { title: "The Calendar War", body: "<p>Then came 1912.</p><p>The newly established Republic of China, eager to modernize and synchronize with the Western world, adopted the Gregorian calendar. January 1st was declared the official New Year. The government marked its calendars, opened its offices, and expected the nation to follow.</p><p>The nation did not follow.</p><p>People ignored the decree entirely and continued celebrating when the moon said to celebrate. This created an awkward situation: a state that existed in one time, and a society that existed in another.</p><p>The solution, proposed in 1914 under Yuan Shikai's government, was a clever piece of bureaucratic wordplay. The Gregorian New Year would be called *Yuandan*—\"First Dawn.\" The lunar celebration would be renamed *Chunjie*—\"Spring Festival\"—a pleasant, agricultural-sounding name that made it seem like a seasonal observance rather than the start of the year.</p><p>It was a compromise. The people could keep their festival; they just couldn't call it New Year anymore. The oldest continuous celebration in human history had been, with the stroke of a pen, demoted to a seasonal holiday.</p>" },
      { title: "Three Abolitions", body: "<p>If the 1914 renaming was a negotiation, what came later was suppression.</p><p>In 1929, the Nationalist government under Chiang Kai-shek decided that compromise was not enough. The lunar calendar was declared abolished. Shops were ordered to stay open on the traditional date. Schools were to hold classes. The message was clear: the future has no room for the past.</p><p>The future didn't cooperate. Merchants invented a tactic called \"half-open shutters\"—they opened their doors to comply with the law, then conducted no business whatsoever. Families celebrated behind closed doors. The countryside simply carried on as if the decree didn't exist.</p><p>Then came 1966, and things got worse.</p><p>The Cultural Revolution was launched in the Year of the Fire Horse—traditionally considered a year of chaos and rupture. Red Guards confiscated firecrackers and destroyed family altars. The Spring Festival holiday was officially cancelled. Workers were told to have a \"Revolutionized and Fighting Spring Festival\"—no rest, no reunion, no tradition.</p><p>And still, people ate dumplings.</p><p>There are memoirs from this period describing families who muffled the sound of chopping meat with quilts. Windows covered with blankets so neighbors couldn't see. The rhythmic *duo-duo-duo* of the cleaver, a quiet code for persistence. In the countryside, even the sent-down urban youth discovered that the peasants—supposedly the vanguard of the revolution—were more attached to the old calendar than anyone.</p><p>Three times in a century, the state tried to abolish or overwrite the celebration. Three times, it failed.</p>" },
      { title: "The Nationalization of Midnight", body: "<p>After Mao's death and China's opening up, the government's relationship with the Spring Festival reversed entirely. Instead of trying to destroy it, the state decided to own it.</p><p>In 1983, China Central Television broadcast its first Spring Festival Gala—a live, synchronized countdown watched by hundreds of millions of people. It was, in effect, the nationalization of midnight.</p><p>Before the Gala, celebrations were local. Each village, each family had its own rhythms, its own songs, its own way of marking the turn. After the Gala, everyone watched the same skits, sang along to the same songs, and counted down the same clock, broadcast from Beijing.</p><p>The Gala became as essential to the holiday as dumplings themselves. Some scholars call it the creation of a \"new folk tradition\"—a televised ritual that unified a vast nation into a single shared experience. Others note the irony: the television replaced the ancestral altar as the focal point of the living room.</p><p>Whether this represents revival or replacement is a question worth sitting with.</p>" },
      { title: "The Politics of a Name", body: "<p>Today, the festival is celebrated across the globe—but what do we call it?</p><p>In China, it's *Chunjie* (Spring Festival) or simply *Guo Nian* (Passing the Year). In Korea, it's Seollal. In Vietnam, it's Tết. In the West, corporations and governments increasingly use \"Lunar New Year\" to acknowledge that many Asian cultures share the calendar.</p><p>This has not been uncontroversial. Some argue that \"Lunar New Year\" erases Chinese heritage—that the calendar, zodiac, and core traditions originated in China and deserve acknowledgment. Others argue that \"Chinese New Year\" is hegemonic—that it implies ownership of something that belongs to multiple cultures.</p><p>The debate is not new. Naming has been political since 1914, when the festival was first stripped of its title. Every time we choose what to call this celebration, we are making a statement about history, ownership, and cultural identity.</p>" },
      { title: "What Survives", body: "<p>If there's one thing the history of this festival teaches, it's that governments are not as powerful as they think.</p><p>The people adapted, resisted, waited—and then, when political winds shifted, emerged with their dumplings and their red paper intact. Perhaps what survives is not the decorations or the food, but something harder to name: a rhythm, a refusal, a belief that time should pause for the people you love.</p><p>In 2026, the cycle returns to the Fire Horse—the same position as 1966, when the festival was driven underground. This time, it enters the year as UNESCO Intangible Cultural Heritage, recognized not just in China but by the world.</p><p>The fire has been many things. It has burned temples and family altars. It has lit firecrackers and television screens.</p><p>But it has never quite gone out.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>每年，都有那么一个时刻，时间会折叠回去。</p><p>火车塞满了回家的打工人。市场堆满了红纸和腊肉。日常生活的节奏明显转变，几乎可以听见——仿佛整个国家在深呼吸之前发出的一声长叹。</p><p>这就是春节——或者叫农历新年，或者叫中国新年，取决于你问的是谁，以及他们带着什么立场。但在我们争论该叫它什么之前，也许该先问一个问题：它是怎么走到今天的？</p><p>答案比你想象的更奇怪。</p>" },
      { title: "在它有名字之前", body: "<p>在中国历史的大部分时间里，并没有\"春节\"这个说法。只有\"年\"——那不是一年中的某个节日，而是年本身，是所有时间转动的枢轴。</p><p>这个庆典在历朝历代中不断演变，无需正式命名。汉代的仪式更加隆重——宫廷典礼、祭祖仪式、社区宴席。到了唐宋时期，烟火和灯会加了进来。明清宫廷把新年庆典变成了持续数周的盛大国家活动。</p><p>但在所有这一切中，庆典只是\"存在着\"。它不需要品牌。年到了，你就过。这跟呼吸一样自然。</p>" },
      { title: "历法之战", body: "<p>然后1912年来了。</p><p>新成立的中华民国急于现代化、与西方世界同步，采用了公历。1月1日被宣布为官方新年。政府在日历上做了标记，机关开门办公，期待全国跟随。</p><p>全国并没有跟随。</p><p>老百姓完全无视这道命令，继续按月亮说的时间庆祝。这造成了一个尴尬的局面：一个存在于一种时间里的国家，和一个存在于另一种时间里的社会。</p><p>1914年，袁世凯政府提出解决方案——一招巧妙的行政文字游戏。公历新年叫\"元旦\"——\"第一个早晨\"。农历庆典则更名为\"春节\"——一个听起来宜人、充满农业气息的名字，让它看起来像个物候节气，而不是一年的开端。</p><p>这是妥协。老百姓可以保留他们的节日，只是不能再叫它\"新年\"了。人类历史上延续最久的庆典，被一纸行政命令降格为一个季节性节日。</p>" },
      { title: "三次废除", body: "<p>如果说1914年的更名是谈判，那后来发生的就是压制。</p><p>1929年，蒋介石领导的国民政府认为妥协还不够。农历被宣布废除。商店被命令在传统日期照常营业。学校必须上课。信息很明确：未来没有过去的位置。</p><p>未来不配合。商人发明了一种叫\"半开门\"的策略——他们打开门以遵守法令，然后一笔生意都不做。家家户户关门庆祝。农村干脆当这道命令不存在。</p><p>然后1966年来了，情况更加严峻。</p><p>文化大革命在火马年发动——传统上被认为是混乱和断裂之年。红卫兵没收鞭炮，砸毁家庭祭坛。春节假期被正式取消。工人被要求过一个\"革命化、战斗化的春节\"——不休息、不团圆、不传统。</p><p>然而，人们还是吃饺子。</p><p>那个时代的回忆录描述着：家人用棉被捂住剁馅的声音，窗户用毯子蒙住以免邻居看见。菜刀有节奏的\"笃笃笃\"声，成了坚持的暗号。在农村，\"知识青年\"——被下放到乡村的城市少年——发现了讽刺的事实：农民，理论上的革命先锋，比任何人都更执着于旧历法。</p><p>在一个世纪里，国家三次试图废除或改写这个庆典。三次都失败了。</p>" },
      { title: "午夜的国有化", body: "<p>毛泽东去世、中国开始开放之后，政府与春节的关系彻底翻转。不再试图摧毁它，国家决定拥有它。</p><p>1983年，中央电视台首次直播春节联欢晚会——一场同步的倒计时，数亿人同时观看。这实际上是对午夜的国有化。</p><p>在春晚之前，庆祝是地方性的。每个村庄、每个家庭都有自己的节奏，自己的歌，自己的迎接新年的方式。春晚之后，所有人看同样的小品，跟唱同样的歌，一起倒数同一个钟声——从北京发出。</p><p>春晚本身成为节日不可或缺的一部分，就像饺子一样。有学者把这称为\"新民俗\"的创造——一个电视仪式将一个庞大的国家统一为单一的共享体验。也有人指出反讽之处：电视取代了祖先牌位，成为客厅的焦点。</p><p>这究竟是复兴还是替代，是一个值得细想的问题。</p>" },
      { title: "一个名字的政治", body: "<p>今天，这个节日在全球庆祝——但我们该叫它什么？</p><p>在中国，它是\"春节\"或简单的\"过年\"。在韩国，是Seollal。在越南，是Tết。在西方，企业和政府越来越多地使用\"Lunar New Year\"（农历新年），以承认多个亚洲文化共享这个日历。</p><p>这并非没有争议。有人认为\"农历新年\"抹杀了中国遗产——日历、生肖和核心传统源于中国，理应得到认可。另一些人认为\"中国新年\"是霸权性的——暗示对属于多元文化之物的独占。</p><p>这场争论并不新鲜。命名自1914年起就是政治的——当时节日第一次被剥夺了它的头衔。每一次我们选择如何称呼这个庆典，我们都在对历史、归属和文化身份做出表态。</p>" },
      { title: "存活之物", body: "<p>如果这个节日的历史教会了我们什么，那就是：政府没有它们自以为的那么强大。</p><p>人们适应、抵抗、等待——然后，当政治风向转变时，带着他们的饺子和红纸重新浮现。也许存活下来的不是装饰或食物，而是某种更难命名的东西：一种节律，一种拒绝，一种相信——时间应该为你爱的人暂停。</p><p>2026年，甲子轮回再次回到火马——与1966年相同的位置，那一年节日被驱入地下。这一次，它以联合国教科文组织非物质文化遗产的身份进入这一年，不仅被中国认可，也被世界认可。</p><p>火曾是许多东西。它烧过庙宇和家庭祭坛。它点亮过鞭炮和电视屏幕。</p><p>但它从未真正熄灭。</p>" },
    ],
  },
  'hktw': {
    narrative: [
      { title: "", body: "<p>In 1966, the Year of the Fire Horse, two cities stood at crossroads that would shape how they celebrate the New Year to this day.</p><p>Hong Kong was still a British colony. Taiwan was under martial law. Both were Chinese societies living outside the People's Republic, and both were navigating the same impossible question: how do you preserve Chinese traditions when China itself is tearing them apart?</p><p>Their answers diverged. And sixty years later, the differences are written into every flower market and firecracker.</p>" },
      { title: "Hong Kong: The Managed Spectacle", body: "<p>Hong Kong's relationship with the Lunar New Year has always been shaped by commerce and constraint.</p><p>Under British rule, Chinese cultural identity was both tolerated and contained. The colonial government recognized the strategic value of festivals—they kept the population content—but also regulated them carefully. Firecrackers were banned in 1967 after the leftist riots, and they have never returned. In their place came government-organized fireworks over Victoria Harbour: beautiful, distant, controlled.</p><p>This pattern—the replacement of raw tradition with managed spectacle—defines much of how Hong Kong celebrates today.</p><p>Take the flower markets. Every year, in the week before New Year, Victoria Park transforms into a temporary city of tents. Thousands of vendors sell kumquat trees, peach blossoms, orchids, and narcissus. The selection is not random; each plant carries specific symbolism. Kumquats represent gold (the Cantonese word *gam* sounds like the word for gold). Peach blossoms must be tightly budded—if they open before New Year's Day, the luck dissipates too early. If they open late, the year starts without blessing.</p><p>The flower market is a masterclass in controlled symbolism. Every purchase is a calibrated wish.</p><p>Then there is Poon Choi—the basin feast. In a city where apartments average 400 square feet and kitchens can barely fit one person, the traditional multi-course reunion dinner is physically impossible for many families. Poon Choi solves this: an entire feast layered into a single metal basin. Roast duck and abalone on top, radish and tofu below, all soaked in rich sauce. It is heritage compressed for the vertical city—efficient, delicious, and profoundly pragmatic.</p>" },
      { title: "Taiwan: The Released Festival", body: "<p>Taiwan's path was different, shaped by a unique political history.</p><p>When the Kuomintang retreated to Taiwan in 1949, they brought with them an obsessive commitment to \"authentic\" Chinese culture—positioning the island as the true guardian of traditions that the mainland was destroying. Traditional festivals were promoted as proof of legitimacy. But beneath the state-sanctioned celebrations, local folk traditions simmered, waiting for democratic freedom to release them.</p><p>That freedom arrived gradually through the 1980s and 1990s, and when it did, Taiwan's New Year celebrations exploded in directions that mainland orthodoxy would never have permitted.</p><p>The most dramatic expression is the Yanshui Beehive Rocket Festival, held on the fifteenth day of the first lunar month. Massive wooden structures loaded with thousands of bottle rockets are stationed along parade routes. When a palanquin carrying the God of War passes by, the structures are ignited. Rockets fire horizontally into the crowd. Participants wear motorcycle helmets, thick jackets, and wet towels, and stand their ground as projectiles impact their bodies. To be hit is to be blessed. To endure the fire is to prove you are alive.</p><p>This is not the careful symbolism of Hong Kong's flower markets. This is catharsis.</p><p>Another distinctly Taiwanese tradition is the Bombing of Master Han Dan in Taitung, an event where a bare-chested man representing the God of Wealth is pelted with firecrackers while being paraded through the streets. The noise is volcanic. The danger is real. And the crowds love it.</p>" },
      { title: "The Food Divide", body: "<p>Even at the dinner table, the two cities diverge.</p><p>In Hong Kong, the reunion dinner revolves around Cantonese culinary precision: whole steamed fish (the word *yú* for fish is homophonous with *yú* meaning surplus), lettuce wraps (the Cantonese *saang choi* sounds like \"generating wealth\"), and sweet rice balls for completeness. Everything is about phonetic luck—food as linguistic prayer.</p><p>In Taiwan, the centerpiece is often *wéi lú*—literally \"surrounding the stove.\" The family gathers around a hot pot or a central flame, and the meal stretches for hours. The emphasis is less on the specific dishes and more on the act of sustained togetherness. The table becomes a bonfire.</p><p>Southern Taiwan preserves traditions that have faded elsewhere: elaborate temple processions, the burning of spirit money in ornate furnaces, puppet shows telling stories of gods and heroes. These are folk practices that the Kuomintang once promoted for political purposes—but which, under democracy, became genuinely owned by the communities that practice them.</p>" },
      { title: "What the Difference Reveals", body: "<p>What Hong Kong and Taiwan share is undeniable: the lunar calendar, the red envelopes, the desire to start the year with noise and fire and family.</p><p>But what they have become reveals two different answers to the same question: how do you preserve tradition when the world demands you change?</p><p>Hong Kong's answer has been to adapt. Make it fit the city. Make it safe, efficient, beautiful. Compress the feast into a basin. Replace the firecracker with a distant government fireworks show. Turn the flower market into a managed spectacle where every petal carries a price tag.</p><p>Taiwan's answer has been to release. Let it be dangerous. Let it be loud. Let the body endure fire. Let the festival prove that cultural freedom is not just political—it is the right to stand in the smoke and say, \"This is ours.\"</p><p>Both are strategies of survival. Both are valid. Both are beautiful in ways the other cannot be.</p><p>As the Fire Horse returns in 2026, the question is not which approach is better. The question is what this year of transformation will bring to each.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>1966年，火马之年，两座城市站在十字路口——这将塑造它们迎接新年的方式，直至今日。</p><p>香港仍是英国殖民地。台湾处于戒严之下。两者都是生活在人民共和国之外的中华社会，都在应对同一个不可能的问题：当中国本身正在撕裂传统时，你如何保存中国传统？</p><p>它们的答案分道扬镳。六十年后，这种差异被写入了每一个花市和每一串爆竹之中。</p>" },
      { title: "香港：被管理的景观", body: "<p>香港与农历新年的关系，始终被商业与制约所塑造。</p><p>在英国统治下，中国文化身份既被容忍也被收纳。殖民政府认识到节日的策略价值——它们让民众安心——但也小心管控。1967年左派暴动后，鞭炮被禁止，此后再未恢复。取而代之的是政府组织的维多利亚港上空烟花：美丽、遥远、可控。</p><p>这种模式——用被管理的景观取代原生传统——定义了香港今天大部分的庆祝方式。</p><p>以花市为例。每年新年前一周，维多利亚公园变成临时帐篷城。数千商贩售卖金桔树、桃花、兰花、水仙。选择并非随意，每种植物都承载特定的象征意义。金桔代表金子（粤语\"柑\"与\"金\"谐音）。桃花必须含苞待放——如果在年初一前就开了，运气会过早散去；如果开得太晚，新年就缺了祝福。</p><p>花市是受控象征学的大师课。每一次购买都是精心校准的祈愿。</p><p>然后是盆菜——盆中的盛宴。在一个公寓平均面积四十平米、厨房勉强容一人的城市里，传统多道大菜的年夜饭对许多家庭来说在物理上就不可能。盆菜解决了这个问题：一整桌盛宴层叠在一个金属盆里。上层是烧鸭、鲍鱼，下层是萝卜、豆腐，全浸在浓郁的酱汁中。这是为垂直城市压缩的遗产——高效、美味、深刻务实。</p>" },
      { title: "台湾：被释放的节日", body: "<p>台湾的路径不同，由独特的政治历史塑造。</p><p>1949年国民党退守台湾时，带来了对\"正宗\"中国文化的执着——将岛屿定位为大陆正在摧毁的传统的真正守护者。传统节日被作为正统性的证明来推广。但在官方节庆之下，地方民间传统在酝酿，等待民主自由来释放它们。</p><p>自由在八十年代和九十年代逐渐到来，当它到来时，台湾的新年庆祝以大陆正统永远不会允许的方向爆发。</p><p>最戏剧性的表达是盐水蜂炮，在正月十五举行。巨大的木结构装满数千支冲天炮，沿巡游路线排开。当抬着关帝的轿子经过时，炮架被点燃。火箭水平射向人群。参与者戴着摩托车头盔、厚夹克、湿毛巾，在炮弹冲击身体时站稳脚跟。被击中即是被祝福。承受火焰即是证明你还活着。</p><p>这不是香港花市的精心象征。这是宣泄。</p><p>另一个独特的台湾传统是台东的炸寒单爷。一名赤裸上身的男子代表财神，在巡游时被围观者用鞭炮轰炸。噪声如火山。危险是真实的。人群乐在其中。</p>" },
      { title: "餐桌上的分野", body: "<p>即使在餐桌上，两座城市也走向不同。</p><p>在香港，年夜饭围绕粤菜的精确性展开：整条清蒸鱼（\"鱼\"与\"余\"谐音），生菜（粤语\"生菜\"谐音\"生财\"），甜汤圆象征圆满。一切关乎语音上的好运——食物即是语言学的祈祷。</p><p>在台湾，核心往往是\"围炉\"——字面意思就是\"围着火炉\"。全家围坐在火锅或中央炉火旁，一顿饭可以延续数小时。重点不在于具体菜品，而在于持续在一起的行为。餐桌变成了一堆篝火。</p><p>南台湾保留了在别处已经褪色的传统：精心的庙会巡游，在华丽的金炉中焚烧纸钱，演绎神明和英雄故事的布袋戏。这些是国民党曾出于政治目的推广的民间习俗——但在民主化之后，被实践它们的社区真正拥有了。</p>" },
      { title: "差异揭示了什么", body: "<p>香港和台湾共享的东西不可否认：农历、红包、在新年伊始用噪音、火焰和家人来开启一年的愿望。</p><p>但它们成为的样子，揭示了对同一个问题的两种不同答案：当世界要求你改变时，你如何保存传统？</p><p>香港的答案是适应。让它适合城市。让它安全、高效、美丽。把盛宴压缩进盆里。用遥远的政府烟花表演取代鞭炮。把花市变成每片花瓣都标了价的精管景观。</p><p>台湾的答案是释放。让它危险。让它吵闹。让身体承受火焰。让节日证明文化自由不仅是政治的——它是站在烟雾中说\"这是我们的\"的权利。</p><p>两者都是生存策略。两者都有效。两者都以对方不能企及的方式展现着美。</p><p>当火马在2026年回归时，问题不是哪种方式更好。问题是：这个转型之年将给每个地方带来什么？</p>" },
    ],
  },
  'overseas': {
    narrative: [
      { title: "", body: "<p>The second new moon after the winter solstice rises over Asia, and in that instant, a single astronomical event triggers a cascade of celebrations—and silences—across a dozen nations.</p><p>The same calendar. The same moon. But beneath it, radically different meanings.</p><p>Because the Lunar New Year does not belong to one culture. It never has. And the story of how it traveled, transformed, and was fought over is as revealing as the festival itself.</p>" },
      { title: "The Calendar That Traveled", body: "<p>The Chinese lunisolar calendar did not stay within China's borders. Through centuries of trade, migration, and imperial influence, it became the temporal framework for much of East and Southeast Asia.</p><p>Korea, Vietnam, and Japan all adopted versions of the Chinese calendar, integrating it with their own astronomical traditions. The twelve-animal zodiac traveled with it, as did many of the ritual practices: ancestral offerings, family reunions, the emphasis on renewal and auspicious beginnings.</p><p>But adoption was never simple imitation. Each culture that received the calendar reshaped it according to its own values, history, and politics. What emerged was not one festival repeated everywhere, but a family of related celebrations—cousins, not copies.</p>" },
      { title: "Japan: The Calendar That Was Erased", body: "<p>Japan provides the most dramatic case of calendar politics.</p><p>In 1873, as part of the Meiji Restoration's modernization campaign, the Japanese government abolished the lunisolar calendar entirely and adopted the Gregorian calendar. January 1st became New Year's Day. The lunar celebration was not merely renamed, as it was in China—it was erased.</p><p>And yet, the zodiac survived. The twelve animals remain central to Japanese culture: birth years still carry personality associations, and the annual *eto* (zodiac animal) appears on New Year's cards, decorations, and temple stamps.</p><p>Most strikingly, the Fire Horse superstition persists. In Japan, the *Hinoe-Uma* year carries a centuries-old belief that women born under the Fire Horse sign are too strong-willed, destined to bring ruin to their households. The legend traces back to the story of Yaoya Oshichi, a greengrocer's daughter in seventeenth-century Edo who committed arson for love and was executed at age sixteen.</p><p>The superstition should have faded. Instead, in 1966—the last Fire Horse year—Japan's birth rate dropped by twenty-five percent. Parents used contraception and abortion at unprecedented rates to avoid having daughters in the \"cursed\" year. The statistical cliff is visible in demographic charts to this day.</p><p>As 2026 approaches—the next Fire Horse year—demographers are watching again. Will modernity finally override a four-century-old fear? Or will the numbers tell the same old story?</p>" },
      { title: "Korea: Sovereignty Through Soup", body: "<p>Korea's relationship with the Lunar New Year is a story of cultural sovereignty.</p><p>During the Japanese occupation of Korea (1910-1945), the colonial government suppressed Korean cultural practices, including the lunar calendar celebrations. The Gregorian New Year was imposed. Korean families who gathered on the lunar date did so in quiet defiance.</p><p>After liberation, *Seollal* slowly returned—but it was not declared a national holiday until 1985, and the full three-day holiday was not restored until 1989. Every bowl of *Tteokguk*—the white rice cake soup consumed on New Year's morning—carries this history. Eating a bowl means aging one year. But it also means participating in an act of cultural reclamation.</p><p>Korean New Year customs differ markedly from Chinese ones. *Charye*, the ancestral rite, involves precise table settings with dried fish to the east and fruit to the west. Deep bows—not firecrackers—define the morning. There are no red envelopes in the Chinese style; instead, elders give *sebaetdon* (New Year's money) after receiving formal bows from younger family members.</p><p>The insistence on distinguishing *Seollal* from \"Chinese New Year\" is not merely semantic. It reflects a history in which celebrating the lunar calendar was, at various points, an act of resistance against both Japanese colonialism and Chinese cultural hegemony.</p>" },
      { title: "Vietnam: The Practical Cat", body: "<p>Vietnam's *Tết Nguyên Đán*—commonly shortened to *Tết*—shares the Chinese calendar but diverges in fascinating ways.</p><p>Most notably, Vietnam replaces the Rabbit with the Cat in the zodiac. Why? Several theories exist: the Vietnamese word for \"rabbit\" (*mão*) sounds like the word for \"cat\" (*mèo*); or perhaps, in a rice-farming culture, the cat—guardian of granaries against rats—was simply more practical than a rabbit.</p><p>The most distinctive Tết custom is *xông đất*—the \"first footer.\" The first person to cross a household's threshold after midnight sets the trajectory for the entire year. This person is carefully chosen: their zodiac sign must be compatible with the household, and they should be prosperous, kind, and auspicious. It is not a casual visit. It is engineered luck.</p><p>The food also diverges: in the north, *bánh chưng*—square sticky rice cakes filled with pork and mung bean, wrapped in banana leaves—represent the earth. In the south, the same concept becomes *bánh tét*, cylindrical rather than square. The shape changes; the meaning endures.</p>" },
      { title: "Southeast Asia: Bridges of Sticky Rice", body: "<p>In the Philippines, Malaysia, Singapore, Thailand, and Indonesia, Lunar New Year celebrations reflect the complex identities of Chinese diaspora communities.</p><p>The Philippines' Binondo district in Manila—the oldest Chinatown in the world, established in 1594—celebrates with *Tikoy*, sweet glutinous rice cakes whose stickiness symbolizes the binding of relationships. The festival is a \"Special Non-Working Holiday,\" declared annually by presidential proclamation—a negotiated cultural position.</p><p>Singapore invented its own tradition in the 1960s: *Yu Sheng*, the Prosperity Toss. Raw fish salad, shredded vegetables, and crackers are tossed high into the air with chopsticks while diners shout auspicious phrases. It is a ritual that did not exist in China. It was created by four Singaporean chefs who understood that diaspora communities need traditions of their own.</p><p>The Prosperity Toss raises a profound question about cultural authenticity. Is a tradition invented in the 1960s less \"real\" than one that dates to the Han Dynasty? Or does the act of creation itself constitute tradition-making?</p>" },
      { title: "What the Moon Connects", body: "<p>The moon rises over Asia, indifferent to borders. But the people below are not indifferent.</p><p>They take the same celestial event and fracture it into a thousand meanings. In Tokyo, the lunar calendar was abolished but the zodiac fears persist. In Seoul, a bowl of soup is an act of sovereignty. In Hanoi, a carefully chosen visitor crosses a threshold to engineer luck. In Manila, sticky rice builds bridges between identities.</p><p>One moon. Many New Years. Each one a story of how cultures choose to measure time—and what they choose to remember.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>冬至后的第二个新月升起在亚洲上空，在那一瞬间，一个单一的天文事件在十几个国家引发了一连串的庆祝——以及沉默。</p><p>同样的历法。同样的月亮。但在它之下，是截然不同的意义。</p><p>因为农历新年不属于一种文化。它从来就不属于。而它如何传播、如何转化、如何被争论的故事，与节日本身一样具有揭示力。</p>" },
      { title: "远行的历法", body: "<p>中国的阴阳合历不曾停留在中国的国境之内。通过几个世纪的贸易、移民和帝国影响，它成了东亚和东南亚大部分地区的时间框架。</p><p>朝鲜、越南和日本都采用了中国历法的版本，并将其同本民族的天文传统融合。十二生肖随历法一同传播，许多仪式习俗也是：祭祖、家庭团聚、对更新与吉祥开端的重视。</p><p>但接受从来不是简单的模仿。每一个接纳历法的文化都按照自己的价值观、历史和政治来重塑它。出现的不是一个节日在各地的复制品，而是一个相关庆典的家族——表亲，而非复制。</p>" },
      { title: "日本：被抹去的历法", body: "<p>日本提供了历法政治最戏剧性的案例。</p><p>1873年，作为明治维新现代化运动的一部分，日本政府彻底废除了阴阳合历，采用公历。1月1日成为新年。农历庆典不仅仅像中国那样被改了名——它被抹去了。</p><p>然而，生肖存活了下来。十二生肖在日本文化中仍然核心：出生年份仍然与性格特征相关联，每年的*干支*（生肖动物）出现在贺年卡、装饰和寺庙印章上。</p><p>最引人注目的是，火马迷信持续存在。在日本，*丙午*年背负着一个几百年的信仰：在火马年出生的女性太刚强，注定给家庭带来毁灭。这个传说追溯至十七世纪江户的八百屋阿七——一个因爱情而纵火、十六岁被处刑的蔬果商之女。</p><p>这个迷信应该已经淡化了。但在1966年——上一个火马年——日本的出生率下降了百分之二十五。父母们以前所未有的比例使用避孕和堕胎，以避免在\"被诅咒\"的年份生下女儿。那个统计悬崖在人口图表中至今清晰可见。</p><p>当2026年——下一个火马年——临近时，人口学家们又在观察。现代性能否最终压倒一个四百年的恐惧？还是数字会讲述同样古老的故事？</p>" },
      { title: "韩国：以汤匙为主权", body: "<p>韩国与农历新年的关系是一个文化主权的故事。</p><p>在日本占领朝鲜半岛期间（1910-1945），殖民政府压制韩国的文化习俗，包括农历节庆。公历新年被强制推行。在农历日期团聚的韩国家庭，只能在安静的抗议中如此行事。</p><p>光复之后，*Seollal*（旧正）缓慢回归——但直到1985年才被定为法定假日，完整的三天假期直到1989年才恢复。每一碗*年糕汤*（Tteokguk）——新年早晨食用的白色年糕清汤——都承载着这段历史。吃一碗意味着长一岁。但它也意味着参与一种文化重申的行为。</p><p>韩国新年的习俗与中国明显不同。*茶礼*（Charye），一种祭祖仪式，要求精确的摆放：干鱼在东、水果在西。深鞠躬——而非鞭炮——定义了这个早晨。没有中式红包；取而代之的是长辈在接受晚辈的正式拜年后给予*岁拜钱*（sebaetdon）。</p><p>坚持将*Seollal*区别于\"中国新年\"不仅是语义问题。它反映了一段历史——在那段历史中，庆祝农历在不同时期都是对日本殖民和中国文化霸权的双重抵抗。</p>" },
      { title: "越南：务实的猫", body: "<p>越南的*Tết Nguyên Đán*——通常简称*Tết*——共享中国历法，但在引人入胜的方面发生了分歧。</p><p>最值得注意的是，越南在生肖中以猫取代了兔。为什么？存在几种理论：越南语\"兔\"（*mão*）与\"猫\"（*mèo*）发音相近；或者也许，在一个稻作文化中，猫——谷仓的守护者、老鼠的捕手——只是比兔子更有用。</p><p>最独特的Tết习俗是*冲年喜*（xông đất）——\"踏门槛\"。午夜过后第一个跨过一户人家门槛的人，将为这一整年定调。此人是精心挑选的：其生肖必须与该户相合，而且应该是成功、善良、光彩的人。这不是随意的拜访。这是被精心设计的运气。</p><p>食物也有分歧：在北方，*粽子*（bánh chưng）——方形的糯米糕，以猪肉和绿豆为馅，包在芭蕉叶里——代表大地。在南方，同一概念变成*bánh tét*，圆柱形而非方形。形状变了；意义延续。</p>" },
      { title: "东南亚：糯米搭的桥", body: "<p>在菲律宾、马来西亚、新加坡、泰国和印尼，农历新年庆祝反映了华人散居社区的复杂身份。</p><p>菲律宾马尼拉的岷伦洛区——世界上最古老的唐人街，建于1594年——以*年糕*（Tikoy）庆祝，这种甜糯米糕的粘性象征着关系的黏合。这个节日是\"特别非工作假日\"，每年由总统公告宣布——一种经过协商的文化定位。</p><p>新加坡在1960年代发明了自己的传统：*鱼生*（Yu Sheng），捞起。生鱼沙拉、切丝蔬菜和饼干用筷子高高抛向空中，食客们同时高喊吉祥话。这是一个在中国并不存在的仪式。它由四位新加坡名厨创造，他们明白离散社区需要属于自己的传统。</p><p>捞起提出了一个关于文化真实性的深刻问题。一个发明于1960年代的传统，是否比追溯到汉代的传统更不\"真实\"？还是说，创造行为本身就构成了传统的诞生？</p>" },
      { title: "月亮连接的", body: "<p>月亮升起在亚洲上空，对边界漠不关心。但下面的人们并非漠不关心。</p><p>他们把同一个天文事件折射成一千种意义。在东京，农历被废除，但生肖的恐惧依旧。在首尔，一碗汤是主权的行为。在河内，一位精心挑选的访客跨过门槛来设计运气。在马尼拉，糯米在身份之间架起桥梁。</p><p>一个月亮。许多新年。每一个都是关于文化如何选择衡量时间——以及它们选择记住什么的故事。</p>" },
    ],
  },
  'zodiac': {
    narrative: [
      { title: "", body: "<p>Four thousand years ago, a court astronomer in the kingdom of Qi noticed something remarkable about a bright wanderer in the night sky.</p><p>The Greeks would later call it Zeus. The Romans would name it Jupiter. But in China, it was known as *Suìxīng*—the Year Star.</p><p>The astronomer observed that every twelve years, Jupiter returned to the same position against the fixed stars. He divided the heavens into twelve stations, and in doing so, planted the seed that would become the Chinese Zodiac.</p><p>This is how an astronomical observation became a system of identity—how the wheel of animals came to govern time, personality, and fate.</p>" },
      { title: "The Twelve Stations", body: "<p>The zodiac system that emerged from Jupiter's orbit is deceptively simple: twelve animals, twelve years, an endless cycle.</p><p>Rat, Ox, Tiger, Rabbit, Dragon, Snake, Horse, Goat, Monkey, Rooster, Dog, Pig—then back to Rat again.</p><p>Where did this specific sequence come from? The origins are genuinely mysterious. The twelve animals appear in Chinese sources by at least the Han Dynasty, but similar zodiac systems exist across East and Southeast Asia, suggesting ancient cultural exchanges whose details are lost to time.</p><p>What is known is that the system was never merely decorative. Each animal governs not only a year but a two-hour period of the day. The Rat rules the hour of midnight—the moment when Yin becomes Yang. The Horse rules noon—when Yang reaches its peak. This temporal mapping reveals the system's cosmological depth: it is not just a calendar but a theory about the rhythm of energy in the universe.</p>" },
      { title: "The Great Race", body: "<p>The most famous origin story of the zodiac is the Great Race—the legend of how the Jade Emperor summoned all the animals and assigned positions based on their order of arrival.</p><p>The Rat, clever and opportunistic, rode on the Ox's back and leapt ahead at the last moment to claim first place. The Dragon, most powerful of all, arrived fifth because he stopped to bring rain to a drought-stricken village. The Pig, who stopped for a meal and a nap, waddled in last.</p><p>It's a charming tale, and it explains the sequence well. But scholars note that the Great Race legend doesn't appear in the earliest zodiac texts. Like the Nian beast legend in the origins of New Year customs, it seems to be a later narrative created to explain a system whose actual origins had grown obscure.</p><p>The real origins likely lie in the intersection of astronomy, agricultural timekeeping, and the totemic traditions of ancient Central Asian peoples. But the Great Race persists because it is a better story than orbital mechanics—and because it assigns each animal a personality that resonates across generations.</p>" },
      { title: "The Five Elements", body: "<p>The zodiac grows significantly more complex when combined with the Five Elements: Wood, Fire, Earth, Metal, Water.</p><p>Each element governs a pair of consecutive years—one Yang, one Yin. Wood is expansive and creative. Fire is transformative and intense. Earth is stabilizing. Metal is precise and decisive. Water is fluid and reflective.</p><p>When the twelve animals and five elements combine, they create the *Sexagenary Cycle*—a sixty-year grand cycle before any animal-element combination repeats. This is the *Jiǎzǐ*, the great wheel of Chinese time, first standardized during the Shang Dynasty and still used today.</p><p>The system means that not all Horse years are alike. A Wood Horse year (most recently 2014) carries different energies than a Water Horse year (2002) or a Fire Horse year (2026). The element colors the animal's nature—amplifying certain qualities, tempering others.</p>" },
      { title: "The Fire Horse", body: "<p>Of all sixty combinations in the cycle, the Fire Horse—*Bǐng Wǔ*—carries perhaps the most charged reputation.</p><p>The Horse already sits at the position of maximum Yang: noon, midsummer, the zenith of solar power. When Fire—itself a Yang element—is added, the result is what classical astrologers called \"double fire.\" It is like noon on the summer solstice: the brightest, most exposed moment possible. Nothing can be hidden.</p><p>In Chinese cosmology, this intensity was regarded with respect but not fear. A Fire Horse year was a time of dynamic transformation, bold action, and radical visibility.</p><p>In Japan, however, the Fire Horse took on a darker legend—and this had devastating real-world consequences.</p>" },
      { title: "The Daughter of Fire", body: "<p>The story centers on Yaoya Oshichi, a greengrocer's daughter in seventeenth-century Edo, born in the Fire Horse year of 1666.</p><p>During a great fire, her family took refuge in a temple where she met a young priest's apprentice. When the family returned home after the fire, Oshichi was separated from her beloved. Desperate to see him again, she set fire to her own family's property, reasoning that a new fire would send them back to the temple.</p><p>She was caught. The fire was contained. But arson was punishable by death. When the magistrate asked her age—knowing that anyone under fifteen would be spared—she answered truthfully: sixteen. She was executed by fire.</p><p>Her story crystallized into a cultural warning specifically in Japan: women born in Fire Horse years were considered too strong, too passionate, destined to \"burn down the household.\" The superstition grew so powerful that by 1966, Japan's birth rate dropped twenty-five percent as parents avoided having daughters in the cursed year.</p><p>This remains one of the most striking examples of how mythology can produce measurable demographic effects—a story so powerful it literally shaped the population structure of a modern nation.</p>" },
      { title: "The Zodiac Heads", body: "<p>The zodiac's cultural weight is also written in bronze.</p><p>In the eighteenth century, Jesuit architects designed a magnificent fountain for the Yuanmingyuan—the Old Summer Palace in Beijing. Twelve bronze animal heads, representing the zodiac, spouted water in sequence: each animal sprayed for its designated two-hour period, and at noon, all twelve fired simultaneously.</p><p>In 1860, British and French troops burned the palace and looted its treasures. The twelve zodiac heads scattered across the world—fragments of Chinese time sold in Western auction houses.</p><p>Over the following century and a half, seven heads were returned to China through a combination of purchases, donations, and diplomatic negotiations. The Horse Head was recovered in 2007 when casino magnate Stanley Ho paid $8.9 million to prevent its auction. It now sits in the National Museum of China.</p><p>Five heads remain missing. The search continues—each recovery a symbolic act of temporal repatriation, a piece of the wheel coming home.</p>" },
      { title: "The Wheel Turns", body: "<p>The zodiac endures because it offers something that linear time cannot: a sense of return.</p><p>In the Western calendar, each year is unique—2025 will never come again. In the Chinese system, time is cyclical. The Fire Horse has come before: in 1906, in 1966. It will come again in 2086. Each return carries the echoes of its predecessors.</p><p>This is not fatalism. It is a framework for understanding patterns—a belief that the energies of certain periods tend to produce certain kinds of events, and that awareness of these patterns is itself a form of wisdom.</p><p>As 2026 approaches, the Fire Horse waits. It carries the memory of Oshichi's fire and Japan's demographic cliff. It carries the weight of looted bronze and returned treasures. And it carries, as it always has, the promise that nothing remains hidden when the light is at its peak.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>四千年前，齐国的一位宫廷天文学家注意到夜空中一颗明亮游星的非凡规律。</p><p>希腊人后来称它为宙斯。罗马人称它为朱庇特。但在中国，它被称为\"岁星\"。</p><p>这位天文学家观察到，每隔十二年，木星就会回到相对于恒星的同一位置。他将天穹分成十二个星次，由此播下了日后成为中国生肖的种子。</p><p>这是一个天文观测如何成为身份系统的故事——动物之轮如何开始主宰时间、性格和命运。</p>" },
      { title: "十二星次", body: "<p>从木星轨道中发展出的生肖系统，看似简单：十二种动物，十二年，无尽循环。</p><p>鼠、牛、虎、兔、龙、蛇、马、羊、猴、鸡、狗、猪——然后又回到鼠。</p><p>这个特定的排列从何而来？起源确实是个谜。十二生肖至少在汉代就出现在中国文献中，但东亚和东南亚各地都存在类似的生肖体系，暗示着细节已随时间流失的古代文化交流。</p><p>已知的是，这个系统从来不仅仅是装饰性的。每只动物不仅主管一年，还主管一天中的两个小时。鼠主管子时（午夜）——阴转阳的时刻。马主管午时（正午）——阳气达到顶峰的时刻。这种时间映射揭示了系统的宇宙论深度：它不仅仅是日历，而是一种关于宇宙中能量节律的理论。</p>" },
      { title: "大赛跑", body: "<p>生肖最著名的起源故事是大赛跑——玉帝召集所有动物、按到达顺序分配排位的传说。</p><p>鼠，聪明又机巧，骑在牛背上，在最后一刻跳到前面抢得第一。龙，万物中最强大的生灵，到了第五名，因为它停下来为干旱的村庄降雨。猪停下来吃了顿饭、打了个盹，最后一个摇摇摆摆走了进来。</p><p>这是一个迷人的故事，很好地解释了排列顺序。但学者们指出，大赛跑的传说并不出现在最早的生肖文献中。就像新年习俗起源中的年兽传说一样，它似乎是后来为解释一个实际起源已不可考的系统而创造的叙事。</p><p>真正的起源很可能在于天文学、农业计时和古代中亚民族的图腾传统的交汇处。但大赛跑的传说之所以流传，是因为它比轨道力学更引人入胜——也因为它赋予了每只动物一种跨越世代引发共鸣的性格。</p>" },
      { title: "五行", body: "<p>当与五行——木、火、土、金、水——结合时，生肖变得显著复杂。</p><p>每种元素主管连续两年——一阳一阴。木是扩展和创造的。火是转化和强烈的。土是稳定的。金是精准和果断的。水是流动和内省的。</p><p>当十二生肖与五行结合，它们创造出*六十甲子*——一个六十年的大循环，之后任何动物-元素组合才会重复。这就是甲子，中国时间的大轮，在商朝首次被标准化，至今仍在使用。</p><p>这意味着并非所有马年都相同。甲午木马年（最近为2014年）与壬午水马年（2002年）或丙午火马年（2026年）承载着不同的能量。元素渲染动物的天性——放大某些特质，调和另一些。</p>" },
      { title: "火马", body: "<p>在六十甲子的所有组合中，火马——丙午——也许承载着最具张力的名声。</p><p>马本就坐落在阳气最盛的位置：正午，仲夏，太阳力量的顶点。当火——本身就是阳性元素——叠加上去，结果就是古典占星家所说的\"双火\"。这就像夏至日的正午：可能的最亮、最无遮蔽的时刻。万物无所遁形。</p><p>在中国的宇宙观中，这种强度被以敬意、而非恐惧来看待。火马年是充满活力变革、大胆行动和彻底可见性的时期。</p><p>然而在日本，火马却承载了更阴暗的传说——并且产生了毁灭性的现实后果。</p>" },
      { title: "火之女", body: "<p>故事的核心是八百屋阿七——十七世纪江户一位蔬果商的女儿，生于丙午火马年（1666年）。</p><p>一场大火中，她的家人在一座寺庙避难，在那里她遇到了一位年轻的僧侣学徒。火灾后家人回到重建的家园，阿七与爱人分离。绝望之中，她放火烧了自己的家，想着新的火灾会把他们再送回寺庙。</p><p>她被抓住了。火被扑灭了。但纵火罪可处死刑。当官员问她的年龄时——知道未满十五岁可免于一死——她如实回答：十六岁。她被处以火刑。</p><p>她的故事在日本凝结成一个特定的文化警示：火马年出生的女性被认为太刚强、太热烈，注定会\"烧毁家庭\"。这个迷信变得如此强大，到1966年，日本的出生率下降了百分之二十五——父母们竭力避免在被诅咒的年份生下女儿。</p><p>这仍然是神话如何产生可测量的人口效应最引人注目的案例之一——一个如此强大的故事，它literally塑造了一个现代国家的人口结构。</p>" },
      { title: "生肖兽首", body: "<p>生肖的文化重量也被铸刻在青铜中。</p><p>十八世纪，耶稣会建筑师为圆明园——北京旧夏宫——设计了一座宏伟的喷泉。十二尊青铜生肖兽首按序喷水：每只动物在它主管的两个时辰喷射，正午时分十二只同时喷涌。</p><p>1860年，英法联军火烧宫殿，洗劫珍宝。十二兽首流散世界各地——中国时间的碎片在西方拍卖行出售。</p><p>在随后的一个半世纪里，七尊兽首通过购买、捐赠和外交谈判回到中国。马首于2007年被回收——赌王何鸿燊支付890万美元阻止拍卖并将其捐赠给国家。它现在陈列于中国国家博物馆。</p><p>五尊兽首仍然下落不明。寻找仍在继续——每一次回收都是一次时间回归的象征行为，轮中的一片碎片回到原处。</p>" },
      { title: "轮转", body: "<p>生肖之所以持久，是因为它提供了线性时间无法给予的东西：一种回归感。</p><p>在西方日历中，每一年都是唯一的——2025永远不会再来。在中国人的时间观念中，时间是循环的。火马曾经来过：1906年，1966年。它将在2086年再次到来。每一次回归都带着前人的回响。</p><p>这不是宿命论。这是理解规律的框架——一种信念，认为某些时期的能量倾向于产生某些类型的事件，而对这些规律的意识本身就是一种智慧。</p><p>当2026年临近，火马等待着。它承载着阿七的焰火和日本的人口悬崖。它承载着被掠夺的青铜和归还的珍宝。而它一如既往地承载着一个承诺：当光在最强处时，万物无可隐藏。</p>" },
    ],
  },
  'customs': {
    narrative: [
      { title: "", body: "<p>When people say they are \"celebrating Chinese New Year,\" they usually mean one night—the reunion dinner, the countdown, the fireworks.</p><p>But the actual festival is an architecture of twenty-three days, beginning on the twenty-third of the twelfth lunar month and ending on the fifteenth of the first. Each day carries its own purpose. Each ritual occupies its appointed position. The whole structure is designed, refined over millennia, to transition an entire civilization from one year to the next.</p><p>To understand the customs is to understand the engineering behind the celebration—the carefully sequenced acts that prepare, purify, feast, renew, and close.</p>" },
      { title: "Seeing Off the Kitchen God", body: "<p>The festival begins, appropriately enough, with a bribe.</p><p>On the twenty-third day of the twelfth month—a date known as *Xiǎonián*, the \"Little New Year\"—families make offerings to Zaojun, the Kitchen God. This deity has spent the entire year sitting above the stove, observing the family's conduct. Now he must ascend to heaven to deliver his annual report to the Jade Emperor.</p><p>The bribe is sticky. Families smear sugar or malt syrup on the lips of his paper effigy—a delicious way to ensure that his mouth is sealed, or failing that, that he can only say sweet things. The paper image is then burned, sending Zaojun skyward. He will return on New Year's Eve, refreshed and reinstalled above the stove, to begin another year of domestic surveillance.</p><p>This is folk religion at its most practical: the divine is approachable, negotiable, and susceptible to sweets.</p>" },
      { title: "The Great Sweeping", body: "<p>After the Kitchen God departs, the purification begins.</p><p>The entire house is swept, scrubbed, and cleaned from top to bottom. This is not housekeeping—it is ritual. The sweeping is directional: you sweep from the inside out, pushing old energy, old luck, old failures toward the door and out of your life. Cobwebs are cleared. Broken items are discarded. Debts should be settled.</p><p>The principle is simple but profound: you cannot receive new blessings into a space still cluttered with last year's dust.</p><p>After the sweeping, the decorating begins. Red *Chūnlián*—Spring Festival couplets—are hung on either side of the doorway. These are not random red strips; each line is composed according to strict rules of parallelism and literary balance. The character *Fú* (fortune) is often hung upside down: the word for \"upside down\" (*dào*) sounds identical to the word for \"arrived\" (*dào*), so an inverted *Fú* means \"fortune has arrived.\"</p><p>This is the Chinese genius for homophonic symbolism—the transformation of language into material magic.</p>" },
      { title: "Reunion Dinner: The Center of Gravity", body: "<p>New Year's Eve—*Chúxī*, the Night of Passing—is when the year turns.</p><p>The reunion dinner is not simply a large meal. It is the gravitational center of the entire festival, the event around which everything else orbits. Families who have scattered across the country return for this one night. The table must be full. An empty seat means an incomplete family.</p><p>The dishes are chosen with care. A whole fish must be served but not entirely consumed—the leftover fish represents *yú*, surplus, a blessing carried into the new year. Dumplings, shaped like ancient gold ingots, embody wealth. Rice cakes (*Niángāo*) promise advancement: the word *gāo* sounds like \"high\" or \"elevated.\" Tangyuan—sweet glutinous rice balls—represent wholeness and unity, the family's circular perfection.</p><p>Every dish is a sentence in an edible language. Every flavor carries a prayer.</p><p>In the south, the emphasis shifts toward rice cakes, whole chickens, and seafood. In the north, dumplings dominate—and the act of making them together, the whole family seated around the kitchen table, is as important as eating them. The filling process is communal; sometimes a coin or a peanut is hidden inside a single dumpling, and whoever bites into it is blessed for the year.</p>" },
      { title: "Shǒusuì: Guarding the Year", body: "<p>After dinner, the family does not sleep.</p><p>*Shǒusuì*—staying up to guard the year—is among the oldest New Year customs. The lights stay on. The house remains illuminated, every room bright, because darkness is where malevolent spirits gather.</p><p>The mythology says that staying awake keeps the family safe through the most dangerous threshold of the year. But the practical effect is just as meaningful: it creates a shared vigil, hours of conversation, card games, television watching (the CCTV Gala since 1983), storytelling. The family is together. The night is long. And by the time midnight arrives, the new year has been earned through collective wakefulness.</p><p>At the stroke of midnight, the world erupts.</p>" },
      { title: "The Morning of the First", body: "<p>The first day of the new year is governed by an elaborate system of protocols.</p><p>You dress in new clothes—preferably red. You greet your elders with specific phrases: *Xīnnián kuàilè* (Happy New Year) is generic; *Gōngxǐ fācái* (Wishing you prosperity) is more traditional. Children receive *Hóngbāo*—red envelopes containing money—but the exchange follows rules. The money must be in even numbers (odd numbers are for funerals). The bills must be new and crisp. The amount should not include the number four (*sì* sounds like death).</p><p>The bow of greeting is precise: left hand over right, because right-hand-over-left is the gesture used at funerals. Getting this wrong is not merely awkward—it is inauspicious.</p>" },
      { title: "What You Must Not Do", body: "<p>Equally important are the prohibitions.</p><p>On the first day: do not sweep (you would sweep away the new year's fortune). Do not use scissors or knives (you might cut your luck). Do not wash your hair (you would wash away prosperity—*fà*, hair, sounds like *fā*, fortune). Do not say unlucky words: death, breaking, losing, emptying.</p><p>Do not break dishes. But if you do—and this is characteristic of the system's practical wisdom—immediately say \"*suì suì píng'ān*\" (peace year after year), because *suì* (broken) sounds like *suì* (year). The language itself provides a remedy for every accident.</p><p>These taboos are not superstitions to be dismissed. They are the behavioral architecture of a period in which every action carries amplified meaning—a few days when the boundary between symbol and reality dissolves.</p>" },
      { title: "Lantern Festival: The Closing of the Circle", body: "<p>The festival officially ends on the fifteenth day of the first month—the first full moon of the new year.</p><p>This is the Lantern Festival, *Yuánxiāo Jié*, a night when cities glow with thousands of illuminated structures. Traditionally, this was the one night of the year when unmarried women were permitted to walk freely in public, making it, in Tang Dynasty poetry, the festival of romantic encounter.</p><p>Riddles are written on lanterns—*Cāi Dēngmí*—and solving them is a communal intellectual exercise. Sweet glutinous rice balls, also called *Yuánxiāo*, are consumed once more, bringing the festival full circle: the round shape echoing the full moon, the sweet filling echoing the family's sweetness.</p><p>The circle closes. The decorations can come down. Normal life resumes.</p><p>But the year has been turned. The house has been swept. The kitchen God is back at his post. And somewhere above, the ledger has been balanced, the reports filed, and a new cycle set in motion.</p><p>Twenty-three days. Thousands of years. The architecture holds.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>当人们说他们在\"过年\"时，通常指的是一个晚上——年夜饭、倒计时、烟花。</p><p>但春节的实际仪式是一座二十三天的建筑，始于腊月二十三，终于正月十五。每一天都有自己的使命。每一个仪式都占据着指定的位置。整座结构经过千年锤炼，旨在将一整个文明从一年过渡到下一年。</p><p>理解习俗就是理解庆典背后的工程学——那些精心排列的行为：准备、净化、宴饮、更新、收束。</p>" },
      { title: "送灶神", body: "<p>节日的开始，恰如其分地，始于一次贿赂。</p><p>腊月二十三——被称为\"小年\"的日子——家家户户向灶王爷献祭。这位神明在灶台上方坐了整整一年，观察着一家人的行为。如今他必须升天，向玉帝递交年度报告。</p><p>贿赂是粘的。人们在他的纸像嘴唇上涂抹糖或麦芽糖——确保他的嘴被封住，或者至少只能说甜言蜜语。然后纸像被焚烧，送灶王爷升天。他将在除夕夜返回，焕然一新地重新安坐灶台之上，开始又一年的家庭\"监察\"。</p><p>这是民间信仰最务实的表达：神是可以接近的、可以商量的，而且经不住甜食的诱惑。</p>" },
      { title: "大扫除", body: "<p>灶神离开后，净化开始。</p><p>整栋房屋从上到下被扫除、擦洗、清理。这不是家务——这是仪式。扫洒有方向：从里往外扫，把旧气、旧运、旧的失败推向门口，推出你的生活。蛛网要清除。破损之物要丢弃。债务应该结清。</p><p>原则简单但深刻：你无法在一个仍然堆满去年灰尘的空间里接收新的祝福。</p><p>扫完之后，装饰开始。红色的春联贴在门框两侧。这不是随意的红纸条：每一行都按照严格的对仗和文学平衡的规则撰写。\"福\"字常常倒着贴——\"倒\"与\"到\"谐音，所以倒福就是\"福到了\"。</p><p>这是中国人的谐音象征天才——将语言转化为物质魔法。</p>" },
      { title: "年夜饭：引力的中心", body: "<p>除夕——\"除\"即交替之夜——是年份转换的时刻。</p><p>年夜饭不仅仅是一顿大餐。它是整个节日的引力中心，是其他一切围绕运转的核心。散居全国各地的家人为了这一晚回来。桌上必须满座。一个空位意味着一个不完整的家。</p><p>菜品的选择精心讲究。必须上一条完整的鱼，但不能全部吃完——剩下的鱼代表\"余\"，一份带入新年的祝福。饺子，形如古代元宝，象征财富。年糕寓意步步高升——\"糕\"与\"高\"谐音。汤圆——甜糯米丸子——代表完整和团圆，家庭的圆满。</p><p>每道菜都是可食语言中的一个句子。每一种味道都承载着一个祈愿。</p><p>南方侧重年糕、整鸡和海鲜。北方则以饺子为主——而全家围坐在厨房桌旁一起包饺子的过程，与吃饺子同样重要。包馅是集体行为；有时一枚硬币或一颗花生被藏在某一个饺子里，谁咬到谁就获得来年的祝福。</p>" },
      { title: "守岁：守护这一年", body: "<p>晚饭之后，一家人不睡觉。</p><p>守岁是最古老的新年习俗之一。灯火不灭。房屋通明，每个房间都亮着，因为黑暗是恶灵聚集之处。</p><p>传说守夜可以保护家人安全度过一年中最危险的门槛。但实际效果同样深远：它创造了一种共同的守望——数小时的交谈、打牌、看电视（1983年起有了春晚）、讲故事。一家人在一起。夜很长。当午夜到来时，新年已经通过集体的清醒被赢得。</p><p>午夜钟声敲响，世界炸开了。</p>" },
      { title: "初一的早晨", body: "<p>新年第一天被一套精密的礼仪体系所统治。</p><p>穿新衣——最好是红色。用特定的短语问候长辈：\"新年快乐\"是通用的；\"恭喜发财\"更为传统。孩子们收到红包——装着钱的红信封——但交换遵循规则。金额必须是双数（单数用于丧事）。钱必须是崭新的纸币。金额不应包含四（\"四\"谐音\"死\"）。</p><p>拜年的手势精准：左手覆右手，因为右手覆左手是丧事的手势。弄错这个不仅仅是尴尬——这是不祥的。</p>" },
      { title: "不能做的事", body: "<p>同样重要的是禁忌。</p><p>初一：不扫地（你会把新年的财气扫走）。不用剪刀或刀（你可能剪断运气）。不洗头（你会洗掉财运——\"发\"，头发，谐音\"发\"，发财）。不说不吉利的话：死、破、丢、空。</p><p>不要打碎碗碟。但如果碎了——这体现了系统的务实智慧——立即说\"岁岁平安\"，因为\"碎\"谐音\"岁\"。语言本身为每一次意外提供了补救。</p><p>这些禁忌不是该被轻视的迷信。它们是一段特殊时期的行为建筑——在这几天里，每一个行为都承载着放大了的意义——符号与现实之间的边界消融了。</p>" },
      { title: "元宵节：圆的收束", body: "<p>节日在正月十五正式结束——新年的第一个满月之夜。</p><p>这就是元宵节，一个城市被千万盏花灯点亮的夜晚。在传统上，这是一年中未婚女性唯一被允许自由出行的夜晚，使之在唐代诗歌中成为浪漫邂逅的节日。</p><p>灯谜写在灯笼上——猜灯谜是一种社区性的智力活动。甜糯米丸子，也叫元宵，再次被端上餐桌，让节日完成闭环：圆的形状呼应满月，甜的馅料呼应家庭的甜蜜。</p><p>圆合上了。装饰可以取下。日常生活恢复。</p><p>但年已经翻过。房屋已经打扫。灶王爷回到了岗位。而在某处之上，账册已经结清，报告已经归档，一个新的循环开始运转。</p><p>二十三天。数千年。这座建筑屹立不倒。</p>" },
    ],
  },
  'goods': {
    narrative: [
      { title: "", body: "<p>In the weeks before Chinese New Year, something changes in the markets.</p><p>The usual rhythm of daily commerce—quick purchases, utilitarian bags of rice, standard vegetables—gives way to something more deliberate. People move through the stalls with purpose, examining dried goods with the concentration of connoisseurs, comparing the amber translucency of dried scallops, the sheen of cured sausages, the tight curl of dried shrimp.</p><p>This is *Bǎn Niánhuò*—\"preparing New Year goods\"—and it is one of the most revealing customs of the festival. Because in Chinese culture, food is never just food, gifts are never just gifts, and the things you bring into your home at the turn of the year are a declaration about what kind of year you intend to have.</p>" },
      { title: "The Logic of Dried Things", body: "<p>Why dried goods? Why not fresh?</p><p>The preference for preserved foods during New Year has practical roots—historically, fresh produce was scarce in winter—but the tradition persists because dried goods embody something that fresh ones cannot: concentrated effort. A dried scallop took sunlight and salt and time. A cured sausage represents weeks of preparation. Dried shrimp, abalone, sea cucumber—these are not convenience foods. They are investments.</p><p>The dried goods also play well with Chinese homophonic symbolism. Dried oysters—*Hàoshì*—sound like \"good things happening.\" Dried moss—*Fàcài*—shares its pronunciation with \"get rich.\" Black moss, in particular, is a nearly tasteless ingredient that appears in dishes purely for its linguistic value. You eat its name more than its flavor.</p><p>This is the material language of Chinese New Year: every purchase is a sentence, every gift is a prayer, and the market is a library of good fortune.</p>" },
      { title: "The Orange Ceremony", body: "<p>Of all New Year exchanges, the giving and receiving of oranges is perhaps the most elegant.</p><p>Mandarin oranges—*Gān*—are homophonous with \"gold\" in multiple Chinese dialects. To present a pair of oranges (always two; odd numbers are reserved for mourning) is to offer, literally, a pair of golden blessings. The recipient must accept them graciously, then reciprocate with their own pair.</p><p>But the ceremony extends beyond the fruit. When visiting during the New Year period, guests bring oranges in pairs. Hosts accept them and place them on the altar or the living room table, then present the visitors with a fresh pair to take home. The oranges circulate through the community like a currency of goodwill—no household should be without them, and no visit should transpire without their exchange.</p><p>The logistics of this can be impressive. A family making multiple New Year visits may handle dozens of oranges in a single afternoon, carefully ensuring that the pairs they give are at least as good as the pairs they receive. There is an art to selecting oranges: the skin should be smooth and taut, the color deep and even, the size substantial without being ostentatious.</p>" },
      { title: "The Pastry Archives", body: "<p>Beijing and the north have their own material language, centered on traditional pastries.</p><p>Sachima—a sticky, shredded pastry bound with malt sugar—originated as a Manchu court food and has become inseparable from the Beijing New Year. Beijing Eight Specialties—*Jīngbā Jiàn*—are a curated set of pastry types, each with its own history and technique: date paste rolls, sweetened bean cakes, sugar-coated ears.</p><p>These pastries are not improvised; they are reproduced according to recipes that have been stable for generations. The consistency is the point. You eat the same pastry your grandmother ate, and her grandmother before that. The flavor is not just sweet—it is continuous.</p><p>In the south, the equivalent is Nian Gao—the sticky rice cake that can be steamed, fried, or baked, and whose name means both \"year cake\" and \"year height,\" promising advancement. In Guangdong, radish cakes (*Luóbo Gāo*) and water chestnut cakes (*Mǎtí Gāo*) join the lineup. Each region curates its own New Year pantry, distinct in ingredients but unified in the principle that food speaks where words fall short.</p>" },
      { title: "Red Envelopes: The Arithmetic of Affection", body: "<p>The *Hóngbāo*—red envelope—is perhaps the most famous New Year gift, and the most misunderstood.</p><p>It is not a tip. It is not a casual gift. It is a precisely calibrated expression of a relationship.</p><p>Red envelopes are given by elders to children, by married couples to unmarried ones, by employers to employees. The amount enclosed follows strict rules: it must be an even number (odd amounts are for funerals). It should not include the digit four (which sounds like death). Common amounts end in eight (which sounds like prosperity). The bills must be new and crisp—old, wrinkled bills would transmit old, wrinkled luck.</p><p>But the amount is also relational. You give your niece more than your colleague's child. You give your direct report more than a distant department's intern. The hierarchy of amounts mirrors the hierarchy of closeness, creating a financial map of social bonds that is updated every year.</p><p>In recent years, digital red envelopes on WeChat have added a new layer. In 2014, WeChat's red envelope feature went viral, allowing users to send randomized amounts to group chats. The gamification of giving—the thrill of opening a digital envelope not knowing whether it contains eight yuan or eighty—transformed an ancient custom into a mobile game.</p><p>Whether this enhanced or diminished the tradition is debated. What is undeniable is that the red envelope survived the transition from paper to pixel, which suggests that its essence was never the paper.</p>" },
      { title: "Làròu: Memory in Salt", body: "<p>Perhaps the most personal of all New Year goods is *Làròu*—cured meat.</p><p>In many parts of China, particularly the southwestern provinces, families begin curing pork and sausages in early winter. The strips of belly pork are rubbed with salt, Sichuan peppercorn, and sometimes liquor, then hung from bamboo poles on balconies and rooftops to dry in the winter sun.</p><p>The result, weeks later, is a deeply flavored, amber-colored meat that is sliced thin and steamed above rice or stir-fried with garlic shoots. It tastes of smoke and time.</p><p>Làròu is almost never purchased. It is made at home, by hand, using techniques passed from parents to children. Each family's recipe is slightly different—a little more pepper, a little less salt, an extra splash of liquor. The flavor is inherited.</p><p>For millions of Chinese people now living in cities far from their home provinces, receiving a package of homemade Làròu from aging parents is one of the most emotionally charged moments of the New Year season. The meat arrives vacuum-sealed or wrapped in newspaper, smelling of the familiar kitchen, carrying the taste of home.</p><p>It is not just food. It is an argument against forgetting.</p>" },
      { title: "What the Goods Carry", body: "<p>The material culture of Chinese New Year reveals something essential about how the festival works.</p><p>It operates through things. Through dried scallops and sticky cakes and red envelopes and cured meat. The celebration is not abstract—it is tactile, edible, exchangeable. You can hold it in your hands, weigh it, taste it.</p><p>And in each of these objects, the same principle recurs: nothing is merely what it appears to be. An orange is gold. A fish is surplus. A cake is advancement. A piece of dried moss is wealth.</p><p>The goods are the festival's vocabulary. And every year, when the markets fill again, the language is spoken anew.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>春节前几周，市场上发生了某种变化。</p><p>日常商贸的节奏——快速购买、实用的米袋、标准蔬菜——让位于更审慎的行为。人们带着目的穿行于摊位之间，以鉴赏家的专注审视干货，比较瑶柱的琥珀透光度、腊肠的光泽、虾米的紧密卷曲。</p><p>这是\"办年货\"——它是节日最具揭示力的习俗之一。因为在中国文化中，食物从来不仅是食物，礼物从来不仅是礼物，而你在岁末送入家门的东西，是关于你打算拥有什么样的一年的宣言。</p>" },
      { title: "干货的逻辑", body: "<p>为什么偏好干货？而不是新鲜的？</p><p>过年偏好腌制食品有其实用根源——历史上，冬季新鲜食材稀缺——但传统延续下来，是因为干货体现了鲜货无法承载的东西：凝缩的心血。一颗瑶柱需要阳光、盐和时间。一根腊肠代表数周的准备。虾米、鲍鱼、海参——这些不是方便食品。它们是投入。</p><p>干货也与中国的谐音象征完美配合。蚝豉——谐音\"好事\"。发菜——与\"发财\"同音。发菜尤其有趣，它几乎无味，出现在菜肴中纯粹是为了它的语言价值。你吃的是它的名字，不是它的味道。</p><p>这就是中国新年的物质语言：每一次购买是一个句子，每一份礼物是一个祈愿，而市场是一座好运的图书馆。</p>" },
      { title: "橙子仪式", body: "<p>在所有新年交换中，橙子的赠予和接收也许是最优雅的。</p><p>柑橘——\"柑\"——在多个中文方言中与\"金\"谐音。赠送一对柑橘（永远是双数；单数留给丧事）就是字面上地送出一对金色的祝福。受赠者须优雅地接受，然后回赠自己的一对。</p><p>但仪式超越了水果本身。拜年时，客人成双携带柑橘。主人接受并将其放置在神台或客厅桌上，然后呈上一对新的让访客带走。柑橘像善意的货币一样在社区中流通——没有哪个家庭应该缺少它们，没有哪次拜访应该在没有交换的情况下发生。</p><p>这件事的后勤可以令人印象深刻。一个在同一个下午进行多次拜年的家庭可能要处理数十个柑橘，仔细确保送出的对至少和收到的对一样好。选柑橘是有讲究的：皮要光滑紧致，颜色深而均匀，大小实在但不张扬。</p>" },
      { title: "糕点档案", body: "<p>北京和北方有自己的物质语言，以传统糕点为核心。</p><p>萨其马——一种用麦芽糖粘合的条状点心——起源于满族宫廷食品，已与北京年节密不可分。京八件——一套精选的糕点品类，每一种都有自己的历史与技艺：枣泥卷、豆沙糕、糖耳朵。</p><p>这些糕点不是即兴创作；它们按照代代稳定的配方复制。一致性才是重点。你吃的是祖母吃过的同样的点心，她的祖母之前也一样。那味道不仅仅是甜——它是连续的。</p><p>在南方，对应的是年糕——可以蒸、煎、烤的糯米糕，其名既指\"年糕\"也寓意\"年高\"，承诺步步高升。在广东，萝卜糕和马蹄糕加入阵容。每个地区策展着自己的年货食品库，食材各异，但统一于同一个原则：言语不及之处，由食物来说。</p>" },
      { title: "红包：情感的算术", body: "<p>红包也许是最著名的新年礼物，也是最被误解的。</p><p>它不是小费。它不是随意的馈赠。它是一种精确校准的关系表达。</p><p>红包由长辈给晚辈，由已婚者给未婚者，由老板给员工。封入的金额遵循严格规则：必须是双数（单数用于丧事）。不应包含数字四（谐音\"死\"）。常见金额以八结尾（谐音\"发\"）。纸币必须是崭新脆硬的——旧的、皱巴巴的钞票会传递旧的、皱巴巴的运气。</p><p>但金额也是关系性的。给侄女的多于给同事孩子的。给直系下属的多于远处部门实习生的。金额的层级映射着亲疏的层级，创造出一张每年更新的社会纽带的财务地图。</p><p>近年来，微信数字红包增添了新一层。2014年，微信红包功能爆发式传播，允许用户在群聊中发送随机金额。给予的游戏化——打开数字红包时不知道里面是八元还是八十元的快感——将古老的习俗变成了移动游戏。</p><p>这是增强还是削弱了传统仍有争议。不可否认的是，红包在从纸到像素的转变中存活了下来，这说明它的本质从来不在于纸。</p>" },
      { title: "腊肉：盐中的记忆", body: "<p>也许所有年货中最私人的是腊肉。</p><p>在中国许多地方，特别是西南省份，家家户户在初冬就开始腌制猪肉和腊肠。五花肉条被搓上盐、花椒，有时还有白酒，然后挂在阳台和屋顶的竹竿上，在冬日阳光中风干。</p><p>几周后的成品，是一种风味醇厚、琥珀色泽的肉，薄切后可蒸在米饭上或与蒜苗同炒。它尝起来有烟火气和时间的味道。</p><p>腊肉几乎从不购买。它在家中手工制作，使用从父母传给子女的技艺。每个家庭的配方略有不同——多一点花椒，少一点盐，多加一勺酒。味道是遗传的。</p><p>对数百万现在生活在远离家乡省份的城市中的中国人来说，收到年迈父母寄来的一包自制腊肉，是过年期间最激动人心的时刻之一。肉被真空包装或用报纸裹着寄到，散发着熟悉厨房的气味，承载着家的味道。</p><p>它不仅仅是食物。它是反对遗忘的论据。</p>" },
      { title: "年货承载的", body: "<p>中国新年的物质文化揭示了节日运作方式的本质。</p><p>它通过\"物\"运作。通过瑶柱和年糕和红包和腊肉。庆典不是抽象的——它是触觉的、可食的、可交换的。你可以握在手中，掂量它，品尝它。</p><p>而在每一件物品中，同样的原则反复出现：没有什么仅仅是它表面的样子。一个柑橘是金。一条鱼是余。一块年糕是晋升。一撮发菜是财富。</p><p>年货是节日的词汇。而每一年，当市场再次热闹起来时，这门语言被重新说出。</p>" },
    ],
  },
  'homebound': {
    narrative: [
      { title: "", body: "<p>Every year, somewhere around mid-January, the world's largest migration begins.</p><p>It is not driven by famine, war, or climate—at least not in the conventional sense. It is driven by a dinner table. A specific dinner table, in a specific house, where a specific family will gather on New Year's Eve, and where your absence would be an incompleteness that no amount of money wired home could remedy.</p><p>This is *Chūnyùn*—the Spring Festival travel season—and the numbers are staggering.</p><p>In 2024, the Chinese transportation system recorded approximately 9 billion passenger trips during the forty-day Chunyun window. To put this in perspective: the entire population of the planet could board a vehicle in China during this period and still need more seats. It is not merely a peak season. It is a gravitational event—as if the entire country, for a few weeks each year, is pulled inward toward a single point: home.</p>" },
      { title: "The Hukou Equation", body: "<p>To understand Chunyun, you must first understand why so many people are so far from home.</p><p>China's *Hùkǒu* system—household registration—ties social services like education, healthcare, and pensions to the place where a person is registered, not where they actually live. A factory worker born in Guizhou but employed in Shenzhen remains, in the eyes of the system, a resident of Guizhou. Their children, back in the village with grandparents, can only attend school where the family is registered.</p><p>This creates a structural separation. An estimated 300 million migrant workers live and labor in cities where they have no permanent rights, earning money they send home to families they see once or twice a year. The reunion dinner is not merely desirable—it is the annual repair of a wound that the economic system reopens every day.</p><p>Chunyun is, in this light, the physical manifestation of a bureaucratic contradiction: a country that needs its workers in the cities but defines their belonging in the villages.</p>" },
      { title: "The Forty-Day Window", body: "<p>The Chunyun period officially spans forty days—fifteen before New Year's Day and twenty-five after. During this window, train stations become encampments. Bus terminals overflow. Airports ration their gates.</p><p>The scale of infrastructure required is extraordinary. China Railway operates a normal daily capacity of roughly 10 million passenger trips. During Chunyun, this surges to over 15 million per day on peak dates. Extra trains—called *Línkè*, or temporary passenger services—are added by the hundreds, their schedules threaded into narrow gaps in existing timetables.</p><p>Highways become rivers of headlights. In particularly congested years, traffic jams on national expressways have lasted for days. Toll booths are opened to allow free passage during the holiday, which only increases the flow. Motorcycle caravans—columns of migrant workers on motorbikes, heading hundreds of kilometers back to rural Guangxi or Guizhou—became iconic images of the early 2010s, representing a class of workers who couldn't afford train tickets and didn't own cars.</p>" },
      { title: "The 12306 War", body: "<p>The battle begins with a ticket.</p><p>China's national rail booking system—12306.cn—opens ticket sales thirty days before departure, and the moment a popular route goes live, millions of users descend on the servers simultaneously. In the early years, the system crashed repeatedly. Scalpers (*Huángniú*, literally \"yellow cattle\") hoarded tickets and resold them at multiples of face value.</p><p>The government's response was technological: real-name registration tied to national ID numbers, anti-bot algorithms, a mobile app with facial recognition. These measures reduced scalping but created new anxieties. WeChat groups formed around ticket-buying strategies. Browser plugins that auto-refreshed the page became essential tools. The phrase *qiǎng piào*—\"to snatch tickets\"—entered the language as a verb describing an annual combat ritual.</p><p>For workers on the lowest rungs, the alternative to 12306 was the green train—the non-air-conditioned, slow-speed trains that still run on many routes. A journey that takes four hours on a high-speed train might take twenty-two on a green train. But the green train is cheaper, and its tickets are easier to get. Its hard bench seats, its cigarette smoke, its instant noodle smell—these are the sensory landscape of Chunyun for hundreds of millions of people.</p>" },
      { title: "The Children Left Behind", body: "<p>The emotional center of Chunyun is often invisible: the children.</p><p>China has approximately 69 million \"left-behind children\"—*Liúshǒu Értóng*—minors whose parents have migrated to cities for work while the children remain in rural areas, raised by grandparents or relatives. For these children, the Spring Festival may be the only time they see their parents all year.</p><p>The reunions are joyful and terrible. Parents arrive exhausted from train journeys, laden with gifts from the city: new clothes, toy phones, snacks in packaging the children have never seen. The children are taller than expected, their dialects thicker, their report cards displayed with pride or anxiety. For a few days, the family is whole. Then the parents leave again, often before the holiday formally ends, because the factory needs them back.</p><p>The phenomenon of left-behind children is one of the defining social realities of modern China—a consequence of urbanization speeds that outpaced institutional reform. Chunyun makes this reality visible, concentrating all the year's longing and separation into a single, compressed window of presence.</p>" },
      { title: "Reverse Chunyun", body: "<p>In recent years, a counter-current has emerged.</p><p>Instead of workers traveling home, some families now travel to the city where their relatives work. Parents visit children in Beijing or Shanghai. Grandparents fly for the first time. The reunion happens in a rented apartment rather than a village home.</p><p>This is \"reverse Chunyun\"—*Fǎnxiàng Chūnyùn*—and it represents a pragmatic inversion of the traditional flow. The government has encouraged it as a way to reduce pressure on the transportation system: tickets heading into cities are abundant while tickets heading out are sold out.</p><p>But reverse Chunyun also represents a deeper cultural shift. The ancestral home—the place where the family altar stands, where the graves must be swept, where the reunion has meaning—is being replaced by wherever the family can be together. Home is becoming less a place and more an act.</p>" },
      { title: "What the Journey Means", body: "<p>The remarkable thing about Chunyun is not its scale—though the scale is astonishing. It is that billions of people, year after year, choose to endure it.</p><p>They choose the crowded trains, the delayed flights, the twenty-hour bus rides, the motorcycle journeys through freezing rain. They choose the exhaustion and expense because the alternative—an empty seat at the dinner table—is unbearable.</p><p>In an age when video calls can connect any two points on earth in an instant, the insistence on physical presence is a powerful statement. It says that some things cannot be transmitted digitally. That sitting across from your mother, eating her dumplings, hearing her voice without a two-second delay—that these things are worth nine billion journeys.</p><p>The roads will clog again next year. The trains will fill. The ticket servers will crash. And the people will come home.</p><p>Because the dinner table waits.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>每年一月中旬的某个时候，世界上最大规模的迁徙开始了。</p><p>它不是由饥荒、战争或气候驱动的——至少不是传统意义上的。驱动它的是一张饭桌。一张特定的饭桌，在一栋特定的房子里，一个特定的家庭将在除夕夜围坐那里——你的缺席将是一种不完整，那是无论汇多少钱回家都无法弥补的。</p><p>这就是春运——春节旅运季——其数字令人震撼。</p><p>2024年，中国交通系统在四十天的春运窗口期内录得约九十亿人次出行。换个角度来看：全球所有人口都可以在这段时期内登上中国的交通工具，而且还不够坐。这不仅仅是旺季。这是一个引力事件——仿佛整个国家，每年有几周时间，被向内拉向一个单一的点：家。</p>" },
      { title: "户口方程式", body: "<p>要理解春运，首先要理解为什么这么多人离家这么远。</p><p>中国的户籍制度将教育、医疗、养老等社会服务绑定在一个人\"登记\"的地方，而不是他们实际居住的地方。一个生在贵州但在深圳打工的工人，在制度眼中仍然是贵州居民。他们的孩子留在老家跟祖父母生活，只能在户籍所在地上学。</p><p>这造成了结构性的分离。据估计有三亿农民工在没有永久权利的城市中生活和劳动，把赚的钱寄回给他们每年只能见一两次的家人。年夜饭不仅仅是\"想要的\"——它是对经济体制每天都在重新撕开的伤口的年度修复。</p><p>从这个角度看，春运是一个行政矛盾的物理表现：一个需要工人在城市里的国家，却把他们的归属定义在农村。</p>" },
      { title: "四十天窗口", body: "<p>春运正式持续四十天——年前十五天，年后二十五天。在这个窗口期内，火车站变成营地，汽车站溢出人流，机场分配登机口。</p><p>所需的基础设施规模非凡。中国铁路日常运力约为一千万人次。春运期间，高峰日涌至每天超过一千五百万人次。数百列临客被加开，其时刻表被穿插在既有时刻表的狭窄间隙中。</p><p>高速公路变成车灯的河流。在特别拥堵的年份，国道上的堵车持续了数日。收费站在节日期间免费通行，却只增加了车流。摩托车大军——骑着摩托车、跨越数百公里返回广西或贵州农村的打工人队伍——成为2010年代初的标志性画面，代表着买不起火车票、也没有汽车的一个劳动者阶层。</p>" },
      { title: "12306之战", body: "<p>战斗从一张票开始。</p><p>中国的全国铁路订票系统——12306.cn——在发车前三十天开售车票，当热门线路开放的那一瞬间，数百万用户同时涌入服务器。早期，系统反复崩溃。黄牛囤积车票，以数倍于面值的价格转售。</p><p>政府的回应是技术性的：与身份证号绑定的实名认证、反机器人算法、带面部识别的手机App。这些措施减少了黄牛但制造了新的焦虑。微信群围绕购票策略组建。自动刷新页面的浏览器插件成为必备工具。\"抢票\"这个词进入了语言，成为描述年度战斗仪式的动词。</p><p>对最底层的工人来说，12306之外的选择是绿皮车——那些仍然运行在许多线路上的非空调慢速列车。高铁四小时的旅程，绿皮车可能要二十二小时。但绿皮车更便宜，票也更好买。硬座板凳、香烟味、泡面的气味——这些是数亿人春运的感官景观。</p>" },
      { title: "被留下的孩子", body: "<p>春运的情感核心往往是看不见的：孩子。</p><p>中国约有六千九百万\"留守儿童\"——父母去城市打工、孩子留在农村由祖父母或亲戚抚养的未成年人。对这些孩子来说，春节可能是他们全年唯一见到父母的时刻。</p><p>团聚是喜悦的，也是残酷的。父母经过漫长的火车旅途筋疲力尽地到达，带着城里的礼物：新衣服、玩具手机、孩子们从未见过包装的零食。孩子比预想的高了，口音更重了，成绩单被骄傲或忐忑地展示。几天之内，家庭是完整的。然后父母又走了，往往在假期正式结束之前就走了，因为工厂需要他们回去。</p><p>留守儿童现象是现代中国最具定义性的社会现实之一——城市化速度超越了制度改革的后果。春运使这一现实可见，将全年的思念与分离浓缩在一个单一的、压缩的在场窗口中。</p>" },
      { title: "反向春运", body: "<p>近年来，一股逆流出现了。</p><p>不是工人回乡，而是家人前往工人所在的城市。父母去北京或上海看望孩子。祖父母第一次坐飞机。团圆发生在一间出租屋里，而不是老家的堂屋。</p><p>这就是\"反向春运\"——它代表了对传统流向的务实倒置。政府鼓励这种做法以减轻交通系统的压力：进城方向的票很充裕，而出城方向则被抢光。</p><p>但反向春运也代表了更深层的文化转变。祖屋——家庭神台所在之处、祖坟需要扫祭之处、团圆有其意义之处——正在被\"只要家人能在一起的地方\"所取代。家正在从一个地点变成一种行为。</p>" },
      { title: "旅途的意义", body: "<p>春运最了不起的不是它的规模——尽管那规模已经惊人。而是数十亿人，年复一年，选择承受它。</p><p>他们选择拥挤的火车、延误的航班、二十小时的大巴、冰雨中的摩托车骑行。他们选择疲惫和花费，因为替代方案——餐桌上的一个空位——是不可承受的。</p><p>在一个视频通话可以瞬间连接地球上任何两点的时代，对物理在场的坚持是一个有力的宣言。它说的是：有些东西不能被数字传输。坐在你母亲对面，吃她包的饺子，听到她的声音没有两秒延迟——这些值得九十亿次旅程。</p><p>明年公路还会堵。火车还会满。服务器还会崩。而人们还是会回家。</p><p>因为饭桌在等着。</p>" },
    ],
  },
  'commerce': {
    narrative: [
      { title: "", body: "<p>Chinese New Year is, among other things, the most concentrated redistribution of wealth in the modern world.</p><p>Consider the numbers. In the weeks surrounding the festival, China's consumer spending surges by hundreds of billions of yuan. Red envelopes alone—both physical and digital—transfer an estimated 800 billion yuan annually. The stock market pauses. Banks run out of crisp new bills. Delivery networks strain under the weight of gift parcels. An entire economy reorganizes itself around a single imperative: the turn of the year.</p><p>But this is not simply commerce. It is an economy of meaning—where every transaction carries symbolic weight and every purchase is, at some level, a prayer.</p>" },
      { title: "The Red Envelope Economy", body: "<p>The most visible form of New Year commerce is the *Hóngbāo*—and it operates less like gift-giving than like a relational accounting system.</p><p>A manager gives envelopes to employees: amounts calibrated to hierarchy, seniority, and performance, but never stated aloud. A grandmother gives envelopes to grandchildren: amounts that have increased exactly with inflation, tracked across decades with unspoken precision. A young professional gives envelopes to siblings' children: the amount must exceed what they received when they were children, adjusted for the giver's current income.</p><p>This is the guanxi economy made tangible. Every envelope encodes a relationship. Every amount communicates a message that would be vulgar to say in words but is perfectly legible in cash. The system is unwritten but remarkably consistent: violate its norms—give too little, give odd numbers, give wrinkled bills—and the social cost is real.</p><p>In 2014, WeChat's digital red envelope feature changed the dynamics entirely. By allowing users to send randomized amounts to group chats—where each recipient opens to discover a different amount—the platform gamified an ancient practice. The thrill of opening a digital envelope not knowing if it contains 0.88 yuan or 88 yuan turned giving into a mobile game.</p><p>By 2024, digital red envelopes accounted for more transfers than physical ones. The ceremony persists, but its medium has changed. Whether anything was lost in the translation from paper to pixel is a question each generation answers differently.</p>" },
      { title: "Cherries from Chile", body: "<p>One of the more improbable stories of the New Year economy involves a fruit from the other side of the world.</p><p>In the early 2000s, Chilean cherry exporters discovered that their harvest season—December through February—aligned perfectly with Chinese New Year demand. Cherries, called *Chēlízi* in Chinese, are red, round, and phonetically close to *the sound of luxury*. They became the perfect New Year gift: premium, imported, visually auspicious, and available in exactly the right season.</p><p>The transformation was rapid. Chile now exports more than 90 percent of its cherry crop to China during this window. Specialized cold-chain logistics were developed to get the fruit from Chilean orchards to Chinese consumers in under 72 hours. Charter planes loaded with nothing but cherries fly across the Pacific at peak season.</p><p>The cherries retail for substantial sums—a gift box can cost hundreds of yuan. But the premium is the point. Gifting Chilean cherries says: I can afford to give you something precious, something that traveled 17,000 kilometers to reach your table.</p><p>This is a trade relationship that did not exist twenty years ago, invented entirely by the gravitational pull of a festival.</p>" },
      { title: "The Reunion Dinner, Industrialized", body: "<p>The reunion dinner—the emotional center of the festival—has become one of its most profitable commercial battlegrounds.</p><p>For families who lack the time, kitchen space, or culinary skill to prepare a multi-course feast, restaurants offer pre-cooked reunion dinner packages. These range from modest sets at a few hundred yuan to luxury editions exceeding ten thousand yuan, featuring abalone, sea cucumber, and premium seafood.</p><p>In recent years, the pre-made meal (*Yùzhì Cài*) industry has exploded. Companies now sell vacuum-sealed, flash-frozen reunion dinner courses that can be reheated in minutes. The packages come in themed sets: \"Cantonese Heritage,\" \"Sichuan Master,\" \"Imperial Court.\" A family can recreate an elaborate feast without lighting a stove.</p><p>This industrialization raises questions that extend beyond food. When the act of cooking was communal—grandmother directing, children peeling garlic, father manning the wok—the reunion dinner was as much about process as product. When the meal arrives pre-made in a delivery box, the togetherness shifts to the table. Something is gained (time, convenience, quality control) and something is subtracted (the shared labor that made the meal a metaphor for the family itself).</p>" },
      { title: "Luxury Brands and the Zodiac", body: "<p>Every major luxury brand now releases a Chinese New Year collection, and the results range from elegant to catastrophic.</p><p>The formula seems simple: take the zodiac animal, apply it to existing products, add red. But the execution is treacherous. Brands that treat the zodiac superficially—slapping a cartoon dragon on a handbag—risk ridicule on Chinese social media. Brands that go too deep risk cultural appropriation accusations from Western audiences. The narrow corridor of acceptable engagement requires genuine cultural literacy.</p><p>Some efforts have succeeded brilliantly. Burberry's 2023 Rabbit Year campaign, shot by photographer Leslie Zhang, captured the melancholy and beauty of family reunion without a single red lantern. It sold out immediately.</p><p>Others have become textbook cases of failure. Dolce & Gabbana's 2018 chopstick advertisement—in which a Chinese model struggled to eat Italian food with chopsticks while a male narrator offered condescending instructions—triggered a boycott that cost the brand an estimated $500 million in Chinese market revenue.</p><p>The pattern reveals a broader truth about the festival's commercial dimension: brands can participate in Chinese New Year, but they cannot shortcut their way to cultural credibility. The symbols are not decorations. They are a language. And speaking a language badly is worse than not speaking it at all.</p>" },
      { title: "The Workers Who Stay", body: "<p>While billions travel home, millions stay.</p><p>Delivery drivers, restaurant workers, security guards, hospital staff, power plant operators—the infrastructure of modern life does not pause for the festival, and someone must keep it running. For these workers, Spring Festival is defined by absence: absent from family, present at work.</p><p>Many employers offer double or triple pay during the holiday. Some provide special meals, group activities, a simulacrum of togetherness. But the economic logic is clear: the festival economy depends on workers who do not participate in the festival. The packages of Chilean cherries, the pre-made reunion dinners, the digital red envelopes—all require human hands and digital infrastructure operating through the night.</p><p>This is the hidden labor behind the celebration—the engines that keep running while the rest of the country pauses. Their contribution is rarely acknowledged, except occasionally in the CCTV Gala, which sometimes features segments honoring \"those who stay at their posts.\" The camera lingers for a moment. Then it cuts back to the song and dance.</p>" },
      { title: "What Commerce Reveals", body: "<p>The festival economy is not a corruption of tradition. It is tradition, expressed in a new register.</p><p>Gift-giving has always been central to Chinese New Year. Markets have always filled in the weeks before the festival. What has changed is not the principle but the scale—and the supply chains that now connect Chilean orchards to Chinese gift boxes, Italian leather to zodiac motifs, Silicon Valley algorithms to ancient envelope customs.</p><p>Commerce, at its best, is a form of care transmitted through objects. At its worst, it reduces meaning to price tags. The Spring Festival economy oscillates between these poles, creating both connection and alienation, extravagance and generosity.</p><p>The market opens again next year. The question, as always, is what you choose to buy—and what you mean by it.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>中国新年，在其他一切之外，还是当代世界最集中的财富再分配。</p><p>看看数字。节前几周，中国消费支出激增数千亿元。仅红包——实体和数字加在一起——每年估计转移8000亿元。股市暂停。银行新钞告罄。物流网络在礼品包裹的重量下吃力运作。一整个经济体围绕一个唯一的使命重新组织自身：更年。</p><p>但这不仅仅是商业。这是一种意义经济——其中每一笔交易都承载象征分量，每一次购买在某种层面上都是一个祈愿。</p>" },
      { title: "红包经济", body: "<p>新年商业最显眼的形式是红包——但它的运作方式不像送礼，更像一套关系会计系统。</p><p>经理给员工发红包：金额按照层级、年资和绩效校准，但从不明说。祖母给孙辈发红包：金额精确地随通胀增长，几十年来以无言的精度追踪。年轻的职业人给兄弟姐妹的孩子发红包：金额必须超过他们自己小时候收到的，根据给予者的当前收入调整。</p><p>这是关系经济的实体化。每个红包都编码了一种关系。每个金额都传达着一个用语言说出来会显得粗俗、但在现金中完全可读的信息。这个系统是不成文的，但极其一致：违反其规范——给太少、给单数、给皱巴巴的钞票——社会成本是真实的。</p><p>2014年，微信数字红包彻底改变了动态。通过允许用户在群聊中发送随机金额——每个接收者打开时发现不同的数字——平台将古老的习俗游戏化了。打开一个数字红包时不知道里面是0.88元还是88元的快感，把给予变成了一个移动端游戏。</p><p>到2024年，数字红包的转账量已超过实体红包。仪式延续着，但媒介变了。从纸到像素的翻译中是否失去了什么，每一代人给出不同的答案。</p>" },
      { title: "来自智利的樱桃", body: "<p>新年经济中最不可思议的故事之一，涉及一种来自地球另一端的水果。</p><p>2000年代初，智利樱桃出口商发现他们的收获季——12月到2月——与中国新年的需求完美吻合。车厘子，红色、圆润，在视觉上吉祥。它们成了完美的新年礼物：高端、进口、视觉讨喜，而且恰好在对的季节供应。</p><p>转型是迅速的。智利现在将超过90%的樱桃出口到中国。专门的冷链物流被开发出来，将水果在72小时内从智利果园送到中国消费者手中。高峰季节，满载樱桃的包机飞越太平洋。</p><p>车厘子的零售价不菲——一盒礼品装可达数百元。但溢价就是重点。赠送智利车厘子说的是：我有能力给你一样珍贵的东西——一样穿越了17,000公里才到达你餐桌的东西。</p><p>这是一种二十年前不存在的贸易关系，完全由一个节日的引力所创造。</p>" },
      { title: "年夜饭的工业化", body: "<p>年夜饭——节日的情感中心——已成为最赚钱的商业战场之一。</p><p>对于缺乏时间、厨房空间或烹饪技能来准备多道大菜的家庭，餐厅提供预制年夜饭套餐。从几百元的简朴套餐到上万元的豪华版——含鲍鱼、海参和高端海鲜。</p><p>近年来，预制菜产业爆发。企业销售真空密封、速冻的年夜饭菜品，几分钟即可加热。套餐以主题分类：\"粤式传承\"、\"川味宗师\"、\"宫廷御宴\"。一家人可以在不点火的情况下重现一桌精致盛宴。</p><p>这种工业化提出了超越食物的问题。当烹饪是集体行为时——祖母指挥，孩子剥蒜，父亲掌勺——年夜饭既关乎过程也关乎成品。当菜肴以外卖盒送达时，团聚转移到了餐桌上。有所得（时间、便利、品质把控），也有所失（那使得这顿饭成为家庭本身隐喻的共同劳动）。</p>" },
      { title: "奢侈品牌与生肖", body: "<p>每个主要奢侈品牌如今都推出中国新年系列，效果从精妙到灾难不等。</p><p>公式看似简单：取当年的生肖动物，贴到现有产品上，加红色。但执行是险途。粗暴对待生肖的品牌——在手提包上贴一个卡通龙——在中国社交媒体上遭到群嘲的风险。入戏太深的品牌又面临西方受众的文化挪用指控。可接受参与的狭窄走廊需要真正的文化素养。</p><p>有些努力取得了辉煌成功。Burberry的2023兔年广告，由摄影师Leslie Zhang拍摄，在没有一盏红灯笼的情况下捕捉了家庭团聚的忧郁与美。立刻售罄。</p><p>另一些则成为失败的教科书案例。Dolce & Gabbana的2018筷子广告——一位中国模特用筷子费劲地吃意大利食物，男性旁白给出居高临下的指导——引发了一场抵制，使品牌在中国市场损失了估计5亿美元的收入。</p><p>这个模式揭示了节日商业维度更深层的真相：品牌可以参与中国新年，但无法走捷径获得文化信誉。符号不是装饰品。它们是一种语言。而把一门语言说得糟糕，比不说更坏。</p>" },
      { title: "留下的人", body: "<p>当数十亿人踏上归途，数百万人留了下来。</p><p>快递小哥、餐厅服务员、保安、医护人员、电厂操作工——现代生活的基础设施不会为节日暂停，必须有人维持它运转。对这些工人来说，春节由缺席定义：缺席于家庭，在场于工作。</p><p>许多雇主在假期提供双倍或三倍工资。有的提供特别餐食、集体活动、团聚的替代品。但经济逻辑是清晰的：节日经济依赖于不参与节日的工人。那些智利车厘子的包裹、预制年夜饭、数字红包——都需要人手和数字基础设施在深夜运作。</p><p>这是庆典背后隐藏的劳动——在全国暂停时继续运转的引擎。他们的贡献很少被承认，偶尔在春晚中出现，以\"致敬坚守岗位的人\"的环节呈现。镜头停留片刻，然后切回歌舞。</p>" },
      { title: "商业揭示的", body: "<p>节日经济不是对传统的腐蚀。它就是传统，以新的音域表达。</p><p>送礼一直是中国新年的核心。市场一直在节前几周就热闹起来。改变的不是原则，而是规模——以及如今连接智利果园与中国礼盒、意大利皮革与生肖图案、硅谷算法与古老红包习俗的供应链。</p><p>商业在最佳状态时，是通过物品传递的关怀。在最差状态时，它将意义简化为价签。春节经济在这两极之间摆荡，同时创造着连接与疏离、奢靡与慷慨。</p><p>市场明年又会开张。问题一如既往：你选择买什么——以及你想表达什么。</p>" },
    ],
  },
  'vision': {
    narrative: [
      { title: "", body: "<p>When the last firecracker fades, when the lanterns come down, when the airports fill again with workers heading back to the cities—what remains?</p><p>This is the question at the heart of every Chinese New Year. Not \"what happened?\" but \"what does it mean?\" Not the mechanics of customs and commerce, but the deeper architecture of why a civilization pauses, resets, and begins again.</p><p>Across the nine topics we have explored—from origins to evolution, from ceremonies to commodities, from the zodiac to the journey home—a pattern has emerged. And this final chapter is an attempt to name it.</p>" },
      { title: "The Persistence of Repetition", body: "<p>The most obvious thing about Chinese New Year is that it repeats.</p><p>This sounds trivial, but the implications are profound. The Western calendar advances linearly: 2025 becomes 2026, which becomes 2027, each year unique and unrepeatable. Time is an arrow.</p><p>The Chinese calendar is a wheel. The sixty-year cycle of the zodiac ensures that every combination of animal and element returns. Your birth year will come around again. Your parents' birth year will come around again. Time is not an arrow but a spiral, touching the same positions while moving through space.</p><p>This cyclical sense of time creates a fundamentally different relationship with the past. In linear time, the past is behind you, getting farther away. In cyclical time, the past is ahead of you, waiting to be encountered again. The Fire Horse of 2026 is not merely a new year—it is a conversation with 1966 and 1906 and every Fire Horse before that.</p><p>Repetition, in this framework, is not stagnation. It is recognition. Each cycle gives you the chance to understand something you missed the last time around.</p>" },
      { title: "The Family as Unit of Time", body: "<p>In the West, the primary unit of social experience is the individual. Birthdays mark individual time. Achievements are personal. The calendar of milestones—graduation, marriage, retirement—tracks a single life.</p><p>In Chinese culture, the primary unit is the family. And the Spring Festival is the mechanism that makes this visible.</p><p>Consider the reunion dinner. It is not a party; there is nothing casual about it. It is a physical demonstration of a theorem: the family exists. Every member present proves the equation. Every empty seat disproves it. The dinner does not celebrate the family—it constitutes it. Without the gathering, the family is an abstraction, a set of related people scattered across geography. With the gathering, it is real.</p><p>This is why Chunyun exists. This is why nine billion trips happen. Not because of obligation or guilt—though these play their part—but because the family requires periodic reassembly to remain a fact rather than a memory.</p>" },
      { title: "The Grammar of Luck", body: "<p>One of the most distinctive features of Chinese New Year is its comprehensive system for managing luck.</p><p>Fish means surplus. Eight means prosperity. Red means protection. Upside-down means arrived. Even the accidents are scripted: break a dish, and you say \"peace for all years,\" and the linguistic override neutralizes the material misfortune.</p><p>This is not superstition in the dismissive Western sense. It is a grammar—a structured system of symbolic relationships that allows people to speak to the universe through food, color, number, and gesture. Every action during the festival period is a statement in this grammar, and competence in the language is a form of cultural literacy.</p><p>The grammar of luck reveals a worldview in which humans are not passive recipients of fate but active participants in shaping it. You can influence the year to come—not through prayer alone, but through precision. The right food. The right words. The right direction of the sweep. The universe is listening, and it understands Chinese.</p>" },
      { title: "The Fire Horse Returns", body: "<p>2026 is the Year of the Fire Horse—the first since 1966.</p><p>In 1966, the Cultural Revolution was launched. Spring Festival was cancelled. Family altars were destroyed. In Japan, a generations-old superstition caused the birth rate to plummet. The Fire Horse, that year, lived up to its reputation for upheaval.</p><p>But upheaval is not the same as destruction. Fire transforms. It burns away what is no longer needed and reveals what can withstand heat. The Fire Horse year is, in classical Chinese cosmology, the year of maximum visibility—when everything hidden is exposed, when truth cannot be avoided.</p><p>In 2026, the festival enters its Fire Horse iteration as UNESCO Intangible Cultural Heritage—globally recognized, commercially powerful, and still, beneath all the spectacle, a family dinner.</p><p>The question is not whether the Fire Horse will bring change. It will. The question is whether we will be present enough to see what it illuminates.</p>" },
      { title: "Ancient and Modern", body: "<p>The tension between tradition and modernity runs through every aspect of the festival.</p><p>Pre-made reunion dinners vs. grandmother's recipe. Digital red envelopes vs. crisp bills in paper. CCTV Gala vs. village storytelling. FaceTime calls vs. physical presence. Chilean cherries vs. homemade Làròu.</p><p>It is tempting to frame this as a decline narrative—to say that the festival is losing its soul, that commerce has overtaken meaning, that convenience has replaced care.</p><p>But the evidence doesn't support this reading. The festival has always changed. The CCTV Gala is only forty years old. The red envelope tradition as we know it is probably no older than the Qing Dynasty. Firecrackers were once bamboo. Every \"tradition\" was once an innovation.</p><p>What persists is not any particular form but the impulse behind it: the need to mark time collectively, to pause together, to declare that this moment—this turn of the wheel—matters.</p>" },
      { title: "What We Carry Forward", body: "<p>The Chinese New Year is not a museum exhibit. It is a living system—adapting, absorbing, transforming—while maintaining a core that has proven remarkably resistant to change.</p><p>That core is simple, although it takes thousands of words and ten chapters to articulate: time is cyclical. The family is the unit of meaning. The material world speaks a symbolic language. And every year, regardless of politics or technology or circumstance, the universe offers a reset.</p><p>The firecracker fades. The lantern comes down. The train pulls away from the station.</p><p>And somewhere, in a kitchen smelling of vinegar and ginger, someone begins to fold dumplings. The pleats must be even—thirteen is traditional, for the thirteen lunar months. The filling must be generous but not so generous that the wrapper tears. The edges must be sealed with care, because a dumpling that opens during cooking spills its fortune into the water.</p><p>It will be eaten tonight. It will be made again next year. And the year after that. And the year after that.</p><p>This is what endures.</p>" },
    ],
    narrativeCN: [
      { title: "", body: "<p>当最后一声爆竹消散，当灯笼取下，当机场再次涌满返城的打工人——剩下的是什么？</p><p>这是每一个中国新年核心的问题。不是\"发生了什么\"而是\"它意味着什么\"。不是习俗和商业的机制，而是一个文明为何暂停、重置、重新开始的深层建筑。</p><p>在我们探索的九个主题中——从肇始到沿革，从俗礼到货殖，从生肖到归途——一个模式浮现了。这最后一个篇章，是给它命名的尝试。</p>" },
      { title: "重复的持续力", body: "<p>中国新年最显而易见的特征是：它重复。</p><p>这听起来平淡，但含义深远。西方日历线性前进：2025变成2026，变成2027，每年独一无二、不可重来。时间是一支箭。</p><p>中国的日历是一个轮。六十年一循环的甲子确保每一种动物与元素的组合都会回归。你的本命年会再来。你父母的本命年会再来。时间不是箭而是螺旋——在空间中行进的同时触碰着相同的位置。</p><p>这种循环的时间感创造了与过去截然不同的关系。在线性时间中，过去在你身后，越来越远。在循环时间中，过去在你前方，等待被再次遭遇。2026年的火马不仅仅是一个新年——它是与1966年、1906年、以及每一个此前的火马年的对话。</p><p>在这个框架中，重复不是停滞。它是重新认识。每一个循环给你机会去理解上一次你错过的东西。</p>" },
      { title: "家庭作为时间的单位", body: "<p>在西方，社会体验的基本单位是个人。生日标记的是个人时间。成就是私人的。里程碑的日历——毕业、结婚、退休——追踪的是单一的生命。</p><p>在中国文化中，基本单位是家庭。而春节是使这一点可见的机制。</p><p>想想年夜饭。它不是一场派对——它没有任何随意的成分。它是一个定理的物理证明：家庭存在。每一个在场的成员证实这个等式。每一个空位否定它。年夜饭不是庆祝家庭——它构成家庭。没有聚会，家庭是一个抽象概念，一组散落在地理空间中的相关的人。有了聚会，它才是真实的。</p><p>这就是春运存在的原因。这就是九十亿次旅程发生的原因。不是因为义务或愧疚——尽管这些也起作用——而是因为家庭需要周期性的重组，才能保持为一个事实而非一段记忆。</p>" },
      { title: "运气的语法", body: "<p>中国新年最独特的特征之一是它那套管理运气的完整体系。</p><p>鱼意味着余。八意味着发。红色意味着保护。倒过来意味着到了。连意外都有脚本：打碎碗碟，你说\"岁岁平安\"，语言学的覆盖中和了物质上的不幸。</p><p>这不是西方轻蔑意义上的迷信。它是一套语法——一个结构化的象征关系系统，允许人们通过食物、颜色、数字和手势向宇宙说话。节日期间的每一个行为都是这套语法中的一个语句，而对这门语言的精通是文化素养的一种形式。</p><p>运气的语法揭示了一种世界观：人类不是命运的被动接受者，而是塑造命运的积极参与者。你可以影响来年——不仅仅通过祈祷，而通过精准。对的食物。对的字。对的扫地方向。宇宙在听，而它懂中文。</p>" },
      { title: "火马回归", body: "<p>2026年是火马年——自1966年以来的第一个。</p><p>1966年，文化大革命发动。春节被取消。家庭祭坛被摧毁。在日本，一个延续数代的迷信导致出生率骤降。那一年的火马，不负其动荡之名。</p><p>但动荡不等于毁灭。火转化。它烧去不再被需要的东西，显现出能经受高温的东西。火马年，在传统的中国宇宙观中，是最大可见性之年——一切隐藏之物被暴露，真相无可回避。</p><p>2026年，这个节日以联合国教科文组织非物质文化遗产的身份进入它的火马轮回——全球认可，商业强大，而在所有的盛况之下，依然是一顿家庭晚餐。</p><p>问题不是火马是否会带来改变。它会的。问题是我们是否足够在场，去看到它所照亮的东西。</p>" },
      { title: "古与今", body: "<p>传统与现代之间的张力贯穿节日的每一个方面。</p><p>预制年夜饭vs.祖母的配方。数字红包vs.新钞票纸红包。春晚vs.村头说书。视频通话vs.肉体在场。智利车厘子vs.自家腊肉。</p><p>把这框架成一个衰落叙事是诱人的——说节日正在丢失灵魂，商业压过了意义，便利取代了用心。</p><p>但证据不支持这种解读。节日一直在变。春晚只有四十多年的历史。我们所知的红包传统大概不超过清代。爆竹曾经是竹子。每一个\"传统\"都曾经是一次创新。</p><p>持续的不是任何特定的形式，而是其背后的冲动：集体标记时间的需要，一起暂停的需要，宣告这个时刻——轮之一转——重要的需要。</p>" },
      { title: "我们带向前方的", body: "<p>中国新年不是博物馆展品。它是一个活的系统——适应、吸收、转化——同时维持着一个被证明对改变有显著抵抗力的核心。</p><p>那个核心是简单的，尽管用了数千字和十个章节来表述：时间是循环的。家庭是意义的单位。物质世界说着一种象征的语言。而每一年，无论政治、技术还是境遇如何，宇宙提供一次重置。</p><p>爆竹消散了。灯笼取下了。火车驶离了站台。</p><p>而某处，在一个弥漫着醋和姜味的厨房里，有人开始包饺子。褶子必须均匀——传统上十三个，对应十三个农历月份。馅料必须慷慨，但不能慷慨到把皮撑破。边缘必须仔细地封合，因为一个在煮的时候裂开的饺子，会把它的福气泄进水里。</p><p>它今晚会被吃掉。明年还会再包。后年也会。大后年也会。</p><p>这就是延续之物。</p>" },
    ],
  },
};
